import { spawn } from "node:child_process";
import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import path from "node:path";
import type { SDKCustomTool, SDKCustomToolContext, SDKJsonValue } from "@cursor/sdk";
const ROOT=path.resolve(process.cwd()),BAK=path.join(ROOT,".console-backups");
const GIT_TO=15000,RUN_TO=30000,TEST_TO=60000;
const FORBIDDEN=[path.join(ROOT,".git"),path.join(ROOT,"node_modules"),path.join(ROOT,".env"),path.join(ROOT,".env.local"),path.join(ROOT,".console-backups"),path.join(ROOT,"data"),path.join(ROOT,"config","secret")];
function as(v:SDKJsonValue|undefined,fb=""):string{return typeof v==="string"?v:fb}
function safe(fp:string):string{const r=path.resolve(ROOT,fp);if(!r.startsWith(ROOT+path.sep)&&r!==ROOT)throw new Error("Forbidden: "+fp);for(const f of FORBIDDEN)if(r.startsWith(f+path.sep)||r===f)throw new Error("Forbidden: "+fp);if(path.basename(r).startsWith(".env"))throw new Error("Forbidden: "+fp);return r}
function exe(cmd:string,args:string[],opts:{timeout?:number,cwd?:string}={}){const to=opts.timeout??RUN_TO;return new Promise<{stdout:string,stderr:string,exitCode:number}>(resolve=>{const c=spawn(cmd,args,{cwd:opts.cwd??ROOT,timeout:to,stdio:["ignore","pipe","pipe"]});let o="",e="";c.stdout.on("data",(d:Buffer)=>{o+=d.toString()});c.stderr.on("data",(d:Buffer)=>{e+=d.toString()});c.on("close",code=>resolve({stdout:o.slice(0,100000),stderr:e.slice(0,100000),exitCode:code??1}));c.on("error",()=>resolve({stdout:o,stderr:e,exitCode:1}))})}
let chg=0;export function resetFileChangeCount(){chg=0}export function getFileChangeCount(){return chg}
function inc(){chg++;if(chg>5)throw new Error("Max 5 edits/session")}
async function ensureBak(){await fs.mkdir(BAK,{recursive:true})}
function bok(fp:string){return path.join(BAK,createHash("sha256").update(path.relative(ROOT,fp)).digest("hex").slice(0,12)+"_"+Date.now()+"_"+path.basename(fp))}
async function readFile(args:Record<string,SDKJsonValue>):Promise<string>{const fp=safe(as(args.filepath));const c=await fs.readFile(fp,"utf-8");const ls=c.split("\n");if(ls.length>5000){const h=2500;return[...ls.slice(0,h),"...[truncated]",...ls.slice(-h)].join("\n")}return ls.map((l,i)=>String(i+1).padStart(6)+"|"+l).join("\n")}
async function searchCode(args:Record<string,SDKJsonValue>):Promise<string>{const a=["-n","--no-heading","--hidden"];const g=as(args.glob||"");if(g)a.push("--glob",g);a.push("--",as(args.query),ROOT);const{stdout,exitCode}=await exe("rg",a,{timeout:10000});if(exitCode!==0&&!stdout.trim())return"No matches found.";return stdout.trim().split("\n").slice(0,30).join("\n")||"No matches found."}
async function editFile(args:Record<string,SDKJsonValue>):Promise<string>{inc();const fp=safe(as(args.filepath)),old=as(args.old_string),nw=as(args.new_string);if(!old)throw new Error("old_string required");if(old===nw)throw new Error("must differ");if((await fs.stat(fp)).size>400000)throw new Error("Too large");const c=await fs.readFile(fp,"utf-8"),n=c.split(old).length-1;if(n===0)throw new Error("not found");if(n>1)throw new Error("appears "+n+" times");await ensureBak();await fs.writeFile(bok(fp),c,"utf-8");const up=c.replace(old,nw);await fs.writeFile(fp,up,"utf-8");const rel=path.relative(ROOT,fp);await exe("git",["add","--",rel],{timeout:GIT_TO});const ad=(up.match(/\n/g)||[]).length-(c.match(/\n/g)||[]).length;const rm=(c.match(/\n/g)||[]).length-(up.match(/\n/g)||[]).length;return"Edited "+rel+" (+"+Math.max(0,ad)+" -"+Math.max(0,rm)+")"}
async function runTests(args:Record<string,SDKJsonValue>):Promise<string>{const a=["vitest","run","--reporter=verbose"];const f=as(args.file||"");if(f)a.push(f);const{stdout,stderr}=await exe("npx",a,{timeout:TEST_TO});const o=stdout+stderr;let p=0,fl=0;const pm=o.match(/(\d+)\s+tests?\s+passed/);if(pm)p=Number(pm[1]);const fm=o.match(/(\d+)\s+tests?\s+failed/);if(fm)fl=Number(fm[1]);return JSON.stringify({passed:p,failed:fl,total:p+fl,output:o.slice(-4000)})}
async function gitDiff():Promise<string>{const{stdout:c}=await exe("git",["diff","--cached","--unified=3"],{timeout:GIT_TO});const{stdout:s}=await exe("git",["diff","--unified=3"],{timeout:GIT_TO});return(c+"\n"+s).trim()||"No uncommitted changes."}
async function applyChanges(args:Record<string,SDKJsonValue>):Promise<string>{const tr=await runTests({});const td=JSON.parse(tr) as {failed:number};if(td.failed>0)throw new Error("Tests failed ("+td.failed+")");const{stdout:st}=await exe("git",["status","--porcelain"],{timeout:GIT_TO});if(!st.trim())return"No changes.";await exe("git",["add","-A","--",":(exclude).git",":(exclude)node_modules",":(exclude).env*",":(exclude).console-backups"],{timeout:GIT_TO});const{stdout:co,stderr:ce}=await exe("git",["commit","-m",as(args.message)||"Console: apply"],{timeout:GIT_TO});resetFileChangeCount();return co+ce||"Applied."}
async function revertChanges():Promise<string>{await exe("git",["checkout","--","."],{timeout:GIT_TO});await exe("git",["clean","-fd","--",":(exclude).git",":(exclude)node_modules",":(exclude).env*"],{timeout:GIT_TO});resetFileChangeCount();try{await fs.rm(BAK,{recursive:true,force:true})}catch{}return"Reverted."}
async function listFiles(args:Record<string,SDKJsonValue>):Promise<string>{const d=safe(as(args.dirpath)||".");const e=await fs.readdir(d,{withFileTypes:true});return e.filter(x=>!x.name.startsWith(".")||x.name===".gitignore").sort((a,b)=>a.isDirectory()&&!b.isDirectory()?-1:!a.isDirectory()&&b.isDirectory()?1:a.name.localeCompare(b.name)).map(x=>x.isDirectory()?x.name+"/":x.name).join("\n")||"(empty)"}
function tool(desc:string,schema:Record<string,SDKJsonValue>,fn:(a:Record<string,SDKJsonValue>)=>Promise<string>):SDKCustomTool{return{description:desc,inputSchema:schema,execute:(a,_c)=>fn(a)}}
let _c:Record<string,SDKCustomTool>|null=null;
export function createConsoleHarnessTools():Record<string,SDKCustomTool>{if(_c)return _c;return _c={read_file:tool("Read file with line numbers.",{type:"object",properties:{filepath:{type:"string"}},required:["filepath"]},readFile),search_code:tool("Search codebase with ripgrep.",{type:"object",properties:{query:{type:"string"},glob:{type:"string"}},required:["query"]},searchCode),edit_file:tool("String replacement in a file.",{type:"object",properties:{filepath:{type:"string"},old_string:{type:"string"},new_string:{type:"string"}},required:["filepath","old_string","new_string"]},editFile),run_tests:tool("Run vitest tests.",{type:"object",properties:{file:{type:"string"}},required:[]},runTests),git_diff:tool("Show uncommitted diff.",{type:"object",properties:{},required:[]},gitDiff),apply_changes:tool("Commit changes (tests must pass first).",{type:"object",properties:{message:{type:"string"}},required:["message"]},applyChanges),revert_changes:tool("Undo all uncommitted changes.",{type:"object",properties:{},required:[]},revertChanges),list_files:tool("List directory contents.",{type:"object",properties:{dirpath:{type:"string"}},required:["dirpath"]},listFiles)}}
