"use client";

import { useCallback, useEffect, useMemo, useRef, useState, useSyncExternalStore } from "react";
import {
  initialWaitStatus,
  isGenericWaitStatus,
  waitStatusAt,
} from "@/lib/tutor-wait-status";
import { tryLocalRecall } from "@/lib/local-recall";
import { tryLocalFacts } from "@/lib/local-facts";
import { recordChallengeOutcome } from "@/lib/challenge-mode";
import {
  flowAdviceLabel,
  flowAdvicePromptNote,
  recordFlowTurn,
  type FlowAdvice,
} from "@/lib/flow-signals";
import {
  buildProactiveInvite,
  dismissProactiveToday,
  isWrongReviewKickoff,
  loadPendingWrongAt,
  markProactiveShown,
  noteReviewStarted,
  noteWrongAnswerAt,
  pendingReviewSet,
  PROACTIVE_IDLE_MS,
  shouldProactiveInvite,
  turnsSinceLastWrong,
  type ProactiveInvite,
} from "@/lib/proactive-nudge";
import {
  addWrongAnswer,
  buildVariantKickoffOpener,
  buildWrongReviewOpener,
  consumeVariantKickoff,
  consumeWrongReviewKickoff,
  skillLabelForText,
} from "@/lib/wrong-answer-store";
import { consumeSubjectStarter } from "@/lib/breadth-map";
import {
  creationOfferLine,
  likesTopicSignal,
  type CreationOffer,
} from "@/lib/creation-offer";
import { recentInterests } from "@/lib/interest-store";
import { reconcileWeeklyGoal } from "@/lib/weekly-goal";
import {
  emotionPromptLines,
  emotionUiLine,
  noteEmotionOutcome,
} from "@/lib/emotion-rhythm";
import { softSendErrorLine } from "@/lib/error-guides";
import { buildParentDailyDigest } from "@/lib/parent-digest";
import { loadCheckMode, saveCheckMode } from "@/lib/parent-pin";
import {
  loadSpeakEnabled,
  loadVoiceId,
  resolveReplyLanguage,
  type TutorVoiceId,
} from "@/lib/voices";
import {
  getActiveConversation,
  loadConversations,
  newSessionId,
  saveConversations,
  accountIdFromUrl,
  sessionIdFromUrl,
  setUrlSession,
  titleFromMessages,
} from "@/lib/storage";
import {
  deleteServerChat,
  hydrateFromServer,
  pushStoreToServer,
  repairMissingMedia,
} from "@/lib/history-sync";
import {
  engagementForPrompt,
  loadEngagement,
  recordLearningTurn,
  type EngagementState,
} from "@/lib/engagement";
import {
  getActiveAccount,
  hydrateAccountsFromServer,
  loadAccounts,
  loadStudentProfile,
  RYAN_ACCOUNT_ID,
  switchAccount,
  syncProfileFromSkills,
  type AccountRecord,
} from "@/lib/student-profile";
import {
  applyMisconceptionToMemory,
  autoAdvanceCheck,
  detectPriorTier,
  hydrateLearningMemoryFromServer,
  loadLearningMemory,
  pushLearningMemoryToServer,
  recordLearningTurnMemory,
  saveLearningMemory,
  serializeLearningMemoryForChat,
  autoGenerateDigest,
  appendDigestToMemory,
  classifyTurnOutcome,
  type LearningMemory,
  type LearningSource,
} from "@/lib/learning-memory";
import {
  deletePhotosFromVault,
  fetchMissingPhotosFromServer,
  ingestStorePhotos,
  pruneVaultToStore,
  putPhotoInVault,
  restoreStorePhotosFromVault,
  vaultIdsFromConversation,
} from "@/lib/photo-vault";
import type { ClientAttachment } from "@/lib/file-payload";
import type {
  ChatMessage,
  ChatQuote,
  ConversationRecord,
  ConversationsStore,
} from "@/lib/types";
import { resolveQuoteForSend } from "@/lib/quote";
import type { SpeakStreamApi } from "../VoiceControls";
import type { ComposerApi } from "../Composer";
import {
  mergeWorksheetPlan,
  parseWorksheetPlanFence,
} from "@/lib/worksheet-planner";
import { parseScratchDiagnosisFence } from "@/lib/scratch-diagnosis";
import { parseMisconceptionFence } from "@/lib/misconceptions";
import { collapseSameDiagramImages } from "@/lib/diagram-lifecycle";
import { inferSkillsFromText } from "@/lib/skill-catalog";
import {
  buildPracticeKickoffMessage,
  clearPracticeOffer,
  deferPracticeOffer,
  dismissPracticeOfferForToday,
  loadPracticeOffer,
  savePracticeOffer,
  type PendingPracticeOffer,
} from "@/lib/session-practice";
import {
  maybeCloseSession,
  recoverMissedSessionCloses,
  stampConversationInList,
  VISIBILITY_CLOSE_DEBOUNCE_MS,
} from "@/lib/session-close";
import {
  buildOpenerKickoffMessage,
  buildSessionOpener,
  markOpenerShown,
  type SessionOpener,
} from "@/lib/session-opener";
import {
  buildPracticeKickoffOpener,
  consumePracticeKickoff,
} from "@/lib/idle-nudge";
import {
  buildTedChallengeKickoffMessage,
  clearTedChallengeResume,
  consumeTedChallengeKickoff,
  detectTedCoherenceSignal,
  peekTedChallengeResume,
  tedLabResumeHref,
} from "@/lib/entertain/ted-challenge-handoff";

import {
  buildHistoryPreview,
  consumeChatStream,
  messageId,
  upsertActive,
} from "./tutor-session-utils";

import {
  commitSessionFocus,
  dismissBreakNudge,
  getSessionElapsedMs,
  pauseSessionTimer,
  resumeSessionTimer,
  shouldShowBreakNudge,
  startSessionTimer,
} from "@/lib/session-timer";

export function useTutorSession() {
  const [ready, setReady] = useState(false);
  const [messagesOpen, setMessagesOpen] = useState(false);
  const [store, setStore] = useState<ConversationsStore | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [agentStatus, setAgentStatus] = useState("");
  const [keyMissing, setKeyMissing] = useState(false);
  const [voiceEnabled, setVoiceEnabled] = useState(true);
  const [voiceId, setVoiceId] = useState<TutorVoiceId>("auto");
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [desktopSidebarOpen, setDesktopSidebarOpen] = useState(true);
  const isLg = useSyncExternalStore(
    (onStoreChange) => {
      const mq = window.matchMedia("(min-width: 1024px)");
      mq.addEventListener("change", onStoreChange);
      return () => mq.removeEventListener("change", onStoreChange);
    },
    () => window.matchMedia("(min-width: 1024px)").matches,
    () => true,
  );
  const [agentPanelOpen, setAgentPanelOpen] = useState(false);
  const [agentPanelMinimized, setAgentPanelMinimized] = useState(false);
  const [engagement, setEngagement] = useState<EngagementState | null>(null);
  const [learningMemory, setLearningMemory] = useState<LearningMemory | null>(
    null,
  );
  const [practiceOffer, setPracticeOffer] = useState<PendingPracticeOffer | null>(
    null,
  );
  const [sessionOpener, setSessionOpener] = useState<SessionOpener | null>(null);
  const [tedReturn, setTedReturn] = useState<{
    talkTitle: string;
    nextQi: number;
    coherent: boolean;
  } | null>(null);
  const [dailyBlurb, setDailyBlurb] = useState<string | null>(null);
  const [breakNudge, setBreakNudge] = useState<{
    minutes: number;
    dismissed: boolean;
  } | null>(null);
  const [emotionLine, setEmotionLine] = useState<string | null>(null);
  // V2 P0 — proactive review invite (report §9.2.2): non-blocking offer after
  // an unanswered wrong answer or an idle return.
  const [proactiveInvite, setProactiveInvite] = useState<ProactiveInvite | null>(
    null,
  );
  const hiddenAtRef = useRef<number | null>(null);
  // V2 P0 — "growth moment" line from the flow signal (report §9.2.1).
  const [flowMoment, setFlowMoment] = useState<string | null>(null);
  // Last turn's flow advice — injected into the NEXT turn's prompt so the LLM
  // can adjust difficulty in ordinary conversations (not just challenge mode).
  const flowAdviceRef = useRef<FlowAdvice>("hold");
  // V2 P1 — interest → creation offer (report §9.1.3).
  const [creationOffer, setCreationOffer] = useState<CreationOffer | null>(null);
  const [accountName, setAccountName] = useState("");
  const [accountId, setAccountId] = useState(RYAN_ACCOUNT_ID);
  const [accounts, setAccounts] = useState<AccountRecord[]>([]);
  const [ttsSpeaking, setTtsSpeaking] = useState(false);
  const [speakingMessageId, setSpeakingMessageId] = useState<string | null>(null);
  const [checkMode, setCheckModeState] = useState(false);
  const setCheckMode = useCallback((on: boolean) => {
    setCheckModeState(on);
    saveCheckMode(on);
  }, []);
  useEffect(() => {
    setCheckModeState(loadCheckMode());
  }, []);
  const scrollerRef = useRef<HTMLDivElement>(null);
  const resetNextRef = useRef(false);
  /** sessionIds that need a fresh Cursor agent on next send */
  const resetIdsRef = useRef<Set<string>>(new Set());
  const speakApiRef = useRef<SpeakStreamApi | null>(null);
  const composerApiRef = useRef<ComposerApi | null>(null);
  const checkModeRef = useRef(false);
  const saveTimerRef = useRef<number | null>(null);
  const waitPhaseTimerRef = useRef<number | null>(null);
  const voiceEnabledRef = useRef(true);
  const voiceIdRef = useRef<TutorVoiceId>("auto");
  const accountIdRef = useRef(RYAN_ACCOUNT_ID);
  const storeRef = useRef<ConversationsStore | null>(null);
  const busyRef = useRef(false);
  const syncRunningRef = useRef(false);
  /** Gates server push until init hydration populates deletionCache (prevents
   *  tombstoned conversations from being re-uploaded on fresh page loads). */
  const hydrationDoneRef = useRef(false);
  const accountsRef = useRef<AccountRecord[]>([]);
  /** When a deep-link pinned an account, don't let roster hydrate overwrite it. */
  const deepLinkAccountRef = useRef<string | null>(null);
  const tedKickoffHandledRef = useRef(false);
  const pendingTedKickoffRef = useRef<string | null>(null);
  /** P0 — when the last assistant message finished, for answer-latency flow signals */
  const lastAssistantAtRef = useRef<number>(Date.now());

  useEffect(() => {
    checkModeRef.current = checkMode;
  }, [checkMode]);

  // --- Single init effect: resolve account first, then load conversations ---
  useEffect(() => {
    let cancelled = false;
    // Deferred so the synchronous init setState batch doesn't trigger
    // react-hooks/set-state-in-effect (the async work below already runs in
    // callbacks and is unaffected).
    const t = setTimeout(() => {
    try {
      // 1. Resolve account synchronously — honor ?account= deep-link first
      let accts = loadAccounts();
      const urlAccount = accountIdFromUrl();
      const urlSession = sessionIdFromUrl();
      if (
        urlAccount &&
        accts.accounts.some((a) => a.id === urlAccount) &&
        urlAccount !== accts.activeId
      ) {
        accts = switchAccount(urlAccount, accts);
        deepLinkAccountRef.current = urlAccount;
      }
      let active = getActiveAccount(accts);
      let aid = active.id;
      accountIdRef.current = aid;

      // 2. Load all per-account client data synchronously
      const enabled = loadSpeakEnabled(aid);
      const vid = loadVoiceId(aid);
      const eng = loadEngagement(aid);
      const mem = loadLearningMemory(aid);
      let conversations = loadConversations(aid);

      // Local deep-link: session already on this account
      if (urlSession && urlSession.length > 4) {
        const exists = conversations.conversations.some(
          (c) => c.sessionId === urlSession,
        );
        if (exists && conversations.activeId !== urlSession) {
          conversations = { ...conversations, activeId: urlSession };
        }
      }

      if (cancelled) return;

      // 3. Batch state updates so React renders once
      setAccountId(aid);
      setAccounts(accts.accounts);
      setAccountName(active.profile.name);
      setVoiceEnabled(enabled);
      voiceEnabledRef.current = enabled;
      setVoiceId(vid);
      voiceIdRef.current = vid;
      setEngagement(eng);
      setLearningMemory(mem);
      setStore(conversations);
      setReady(true);
      if (urlSession && urlSession.length > 4) {
        setUrlSession(urlSession, aid);
      }

      // 4. Non-blocking background work
      void hydrateLearningMemoryFromServer(aid).then((m) => {
        if (!cancelled) setLearningMemory(m);
      });

      // Hydrate accounts from server so they're shared across devices
      void hydrateAccountsFromServer().then((hydrated) => {
        if (cancelled) return;
        setAccounts(hydrated.accounts);
        // Never clobber a deep-link account with server "last active"
        if (deepLinkAccountRef.current) return;
        const fresh = getActiveAccount(hydrated);
        if (fresh.id !== accountIdRef.current) {
          setAccountId(fresh.id);
          setAccountName(fresh.profile.name);
        }
      });

      // Photo vault → server hydration; also resolve cross-account deep-links
      void (async () => {
        try {
          let workingAid = aid;
          let workingStore = conversations;

          // Session in URL but not on current account → look up owner on server
          const needLookup =
            !!urlSession &&
            urlSession.length > 4 &&
            !workingStore.conversations.some((c) => c.sessionId === urlSession);

          if (needLookup) {
            try {
              const res = await fetch(
                `/api/history?lookupSession=${encodeURIComponent(urlSession)}`,
              );
              if (res.ok) {
                const data = (await res.json()) as {
                  accountId?: string;
                  conversation?: ConversationRecord;
                };
                const ownerId = data.accountId;
                if (ownerId && ownerId !== workingAid) {
                  // Persist switch + reload that account's local store
                  const switched = switchAccount(ownerId);
                  deepLinkAccountRef.current = ownerId;
                  workingAid = ownerId;
                  accountIdRef.current = ownerId;
                  const ownerAcct = getActiveAccount(switched);
                  if (!cancelled) {
                    setAccounts(switched.accounts);
                    setAccountId(ownerId);
                    setAccountName(ownerAcct.profile.name);
                    setVoiceEnabled(loadSpeakEnabled(ownerId));
                    voiceEnabledRef.current = loadSpeakEnabled(ownerId);
                    const oVid = loadVoiceId(ownerId);
                    setVoiceId(oVid);
                    voiceIdRef.current = oVid;
                    setEngagement(loadEngagement(ownerId));
                    setLearningMemory(loadLearningMemory(ownerId));
                    void hydrateLearningMemoryFromServer(ownerId).then((m) => {
                      if (!cancelled && accountIdRef.current === ownerId) {
                        setLearningMemory(m);
                      }
                    });
                  }
                  workingStore = loadConversations(ownerId);
                }
                // Seed conversation from lookup so UI has it before full hydrate
                if (
                  data.conversation?.sessionId === urlSession &&
                  !workingStore.conversations.some(
                    (c) => c.sessionId === urlSession,
                  )
                ) {
                  workingStore = {
                    ...workingStore,
                    activeId: urlSession,
                    conversations: [
                      data.conversation,
                      ...workingStore.conversations,
                    ],
                  };
                } else if (urlSession) {
                  workingStore = { ...workingStore, activeId: urlSession };
                }
                if (!cancelled) {
                  setStore(workingStore);
                  setUrlSession(urlSession, workingAid);
                }
              }
            } catch {
              // lookup failed — continue with current account hydrate
            }
          }

          await ingestStorePhotos(workingStore);
          const merged = await hydrateFromServer(workingStore, workingAid);
          let withActive = merged;
          if (
            urlSession &&
            urlSession.length > 4 &&
            merged.conversations.some((c) => c.sessionId === urlSession) &&
            merged.activeId !== urlSession
          ) {
            withActive = { ...merged, activeId: urlSession };
          }
          const restored = await restoreStorePhotosFromVault(withActive);
          const fetched = await fetchMissingPhotosFromServer(restored);
          const { store: repaired } = await repairMissingMedia(
            fetched,
            workingAid,
          );
          const final = repaired !== fetched ? repaired : fetched;
          await ingestStorePhotos(final);
          await pruneVaultToStore(final);
          if (cancelled || accountIdRef.current !== workingAid) return;
          setStore(final);
          saveConversations(final, workingAid);
          if (urlSession && urlSession.length > 4) {
            setUrlSession(urlSession, workingAid);
          }
          const withMedia = await pushStoreToServer(final, workingAid);
          if (cancelled || accountIdRef.current !== workingAid) return;
          if (withMedia !== final) {
            setStore(withMedia);
            saveConversations(withMedia, workingAid);
          }
        } catch {
          // Background hydration failures are non-critical — the UI is already live
        } finally {
          // Allow debounce pushes now that deletionCache has been populated (or
          // the fetch definitively failed — holding the gate forever is worse).
          hydrationDoneRef.current = true;
        }
      })();

      // API key check — non-critical, defaults to server-side default key
      fetch("/api/setup")
        .then(async (r) => {
          if (cancelled) return;
          const data = (await r.json()) as { configured?: boolean };
          setKeyMissing(data.configured === false);
        })
        .catch(() => {
          if (!cancelled) setKeyMissing(false);
        });
    } catch (e) {
      // If init itself crashes, show the error instead of infinite loading
      console.error("Spark init failed", e);
      if (!cancelled) {
        setError("Something went wrong. Please refresh the page to try again.");
        setReady(true);
      }
    }
    }, 0);

    return () => {
      cancelled = true;
      clearTimeout(t);
    };
    // One-time init intentionally reads the initial accountId from the closure.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    accountIdRef.current = accountId;
  }, [accountId]);

  useEffect(() => {
    accountsRef.current = accounts;
  }, [accounts]);

  useEffect(() => {
    storeRef.current = store;
  }, [store]);

  useEffect(() => {
    busyRef.current = busy;
  }, [busy]);

  useEffect(() => {
    voiceEnabledRef.current = voiceEnabled;
  }, [voiceEnabled]);

  useEffect(() => {
    voiceIdRef.current = voiceId;
  }, [voiceId]);

  const setSpeakApi = useCallback((api: SpeakStreamApi | null) => {
    speakApiRef.current = api;
  }, []);

  const stopSpeakAll = useCallback(() => {
    speakApiRef.current?.stop();
    setSpeakingMessageId(null);
  }, []);

  // Debounce localStorage + server sync while streaming — sync writes freeze the UI on iPad
  useEffect(() => {
    if (!ready || !store) return;
    if (saveTimerRef.current) window.clearTimeout(saveTimerRef.current);
    const delay = busy ? 1500 : 280;
      saveTimerRef.current = window.setTimeout(() => {
      saveConversations(store, accountId);
      if (!busy && hydrationDoneRef.current) {
        void (async () => {
          await ingestStorePhotos(store);
          const withMedia = await pushStoreToServer(store, accountId);
          // The account may have switched while this push was in flight —
          // never apply a stale store onto the new account's UI.
          if (accountIdRef.current !== accountId) return;
          if (withMedia !== store) {
            setStore(withMedia);
          }
        })();
      }
    }, delay);
    return () => {
      if (saveTimerRef.current) window.clearTimeout(saveTimerRef.current);
    };
  }, [ready, store, busy, accountId]);

  // Periodic cross-device sync: pull deletions + new messages + account changes
  // from the server every 60s and whenever the tab becomes visible again. A
  // conversation that was deleted on another device disappears from this screen
  // without reload. New accounts created on other devices also appear.
  useEffect(() => {
    if (!ready) return;
    const sync = async () => {
      const cur = storeRef.current;
      // Snapshot the account at sync start — the async awaits below may cross
      // an account switch, and reading accountIdRef.current afterwards would
      // save the previous account's store under the new account's key.
      const syncAccountId = accountIdRef.current;
      if (!cur || busyRef.current || syncRunningRef.current) return;
      syncRunningRef.current = true;
      try {
        // 1. Sync account list (new accounts / remote deletions)
        const hydratedAccts = await hydrateAccountsFromServer();
        // Abort if the user switched accounts while this request was in flight.
        if (accountIdRef.current !== syncAccountId) return;
        // Check for remote account deletions / additions
        const curAcc = accountsRef.current;
        const curIds = new Set(curAcc.map((a) => a.id));
        const acctsChanged =
          hydratedAccts.accounts.length !== curAcc.length ||
          !hydratedAccts.accounts.every((a) => curIds.has(a.id));
        // 2. Sync conversations
        const merged = await hydrateFromServer(cur, syncAccountId);
        const restored = await restoreStorePhotosFromVault(merged);
        const fetched = await fetchMissingPhotosFromServer(restored);
        // Upload local-only media (browser has dataUrl, server missing file)
        const { store: repaired } = await repairMissingMedia(
          fetched,
          syncAccountId,
        );
        const final = repaired !== fetched ? repaired : fetched;
        const convsChanged =
          final.activeId !== cur.activeId ||
          JSON.stringify(final.conversations) !==
            JSON.stringify(cur.conversations);
        if (accountIdRef.current !== syncAccountId) return;
        if (convsChanged) {
          setStore(final);
          saveConversations(final, syncAccountId);
        }
        if (acctsChanged) {
          setAccounts(hydratedAccts.accounts);
          // If the active account was deleted remotely, switch to the first available
          const stillActive = hydratedAccts.accounts.some(
            (a) => a.id === accountIdRef.current,
          );
          if (!stillActive) {
            const fallback = hydratedAccts.accounts[0];
            if (fallback) {
              accountIdRef.current = fallback.id;
              setAccountId(fallback.id);
              setAccountName(fallback.profile.name);
              const nextStore = loadConversations(fallback.id);
              setStore(nextStore);
              saveConversations(nextStore, fallback.id);
            }
          }
        }
      } catch {
        // offline — next cycle retries
      } finally {
        syncRunningRef.current = false;
      }
    };
    const timer = window.setInterval(sync, 60_000);
    const onVisible = () => {
      if (document.visibilityState === "visible") void sync();
    };
    document.addEventListener("visibilitychange", onVisible);
    return () => {
      window.clearInterval(timer);
      document.removeEventListener("visibilitychange", onVisible);
    };
  }, [ready]);

  // A2.h.3 — debounced close when tab/app goes hidden (≥30s)
  useEffect(() => {
    if (!ready) return;
    let hideTimer: number | null = null;
    const onVis = () => {
      if (document.visibilityState === "hidden") {
        hideTimer = window.setTimeout(() => {
          const s = storeRef.current;
          if (!s || busyRef.current) return;
          const leaving = getActiveConversation(s);
          const mem = learningMemory || loadLearningMemory(accountIdRef.current);
          const closed = maybeCloseSession(
            leaving,
            mem,
            accountIdRef.current,
          );
          if (!closed.closed) return;
          const conversations = stampConversationInList(
            s.conversations,
            leaving.sessionId,
            closed.conversation,
          );
          const next = { ...s, conversations };
          setStore(next);
          saveConversations(next, accountIdRef.current);
          if (closed.offer) setPracticeOffer(closed.offer);
        }, VISIBILITY_CLOSE_DEBOUNCE_MS);
      } else if (hideTimer != null) {
        window.clearTimeout(hideTimer);
        hideTimer = null;
      }
    };
    document.addEventListener("visibilitychange", onVis);
    return () => {
      document.removeEventListener("visibilitychange", onVis);
      if (hideTimer != null) window.clearTimeout(hideTimer);
    };
  }, [ready, learningMemory]);

  // Visibility: pause/resume session timer + poll break nudge
  useEffect(() => {
    if (!ready) return;
    const onVis = () => {
      if (document.visibilityState === "hidden") {
        pauseSessionTimer();
      } else {
        resumeSessionTimer();
      }
    };
    document.addEventListener("visibilitychange", onVis);
    // Poll break nudge every 10s while active
    const nudgeTimer = window.setInterval(() => {
      if (document.visibilityState === "hidden") return;
      if (shouldShowBreakNudge()) {
        const mins = Math.round(getSessionElapsedMs() / 60_000);
        setBreakNudge({ minutes: mins, dismissed: false });
      }
    }, 10_000);
    return () => {
      document.removeEventListener("visibilitychange", onVis);
      window.clearInterval(nudgeTimer);
    };
  }, [ready]);

  // A2.h.4 — missed-close recovery once store is ready
  useEffect(() => {
    if (!ready || !store) return;
    const mem = learningMemory || loadLearningMemory(accountId);
    const { conversations, offer } = recoverMissedSessionCloses(
      store.conversations,
      mem,
      accountId,
    );
    const changed = conversations.some(
      (c, i) => c.practiceOfferEmittedAt !== store.conversations[i]?.practiceOfferEmittedAt,
    );
    if (!changed) return;
    const next = { ...store, conversations };
    setStore(next);
    saveConversations(next, accountId);
    if (offer && messages.length === 0) setPracticeOffer(offer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ready, accountId]);

  const active = useMemo(
    () => (store ? getActiveConversation(store) : null),
    [store],
  );
  const sessionId = active?.sessionId ?? "";
  const messages = active?.messages ?? [];

  // V2 P0 — proactive review invite (report §9.2.2).
  // Shows a non-blocking offer when (a) a wrong answer went unanswered for a
  // few turns, or (b) the child returns after being away ≥ PROACTIVE_IDLE_MS.
  // Frequency/dismissal guards live in proactive-nudge.ts.
  useEffect(() => {
    if (!ready) return;

    const maybeShowRecentWrong = () => {
      if (busy) return;
      const pendingAt = loadPendingWrongAt(accountId);
      const turns = turnsSinceLastWrong(messages, pendingAt);
      if (
        shouldProactiveInvite(accountId, {
          reason: "recent-wrong",
          pendingAt,
          turnsSince: turns,
        })
      ) {
        const items = pendingReviewSet(accountId);
        if (items.length > 0) {
          markProactiveShown(accountId);
          setProactiveInvite(buildProactiveInvite(items, "recent-wrong"));
        }
      }
    };

    const maybeShowIdleReturn = () => {
      if (busy) return;
      const hiddenAt = hiddenAtRef.current;
      if (hiddenAt == null || Date.now() - hiddenAt < PROACTIVE_IDLE_MS) return;
      if (!shouldProactiveInvite(accountId, { reason: "idle-return" })) return;
      const items = pendingReviewSet(accountId);
      if (items.length === 0) return;
      hiddenAtRef.current = null;
      markProactiveShown(accountId);
      setProactiveInvite(buildProactiveInvite(items, "idle-return"));
    };

    maybeShowRecentWrong();

    const onVis = () => {
      if (document.visibilityState === "hidden") {
        hiddenAtRef.current = Date.now();
      } else {
        maybeShowIdleReturn();
      }
    };
    document.addEventListener("visibilitychange", onVis);
    return () => document.removeEventListener("visibilitychange", onVis);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [messages, busy, ready, accountId]);

  // CA-2 / CA-3 — hydrate empty-chat offers when account or active chat changes
  useEffect(() => {
    if (!ready || !store) return;
    if (messages.length > 0) {
      setPracticeOffer(null);
      setSessionOpener(null);
      return;
    }
    const offer = loadPracticeOffer(accountId);
    setPracticeOffer(offer);
    if (!offer) {
      const mem = learningMemory || loadLearningMemory(accountId);
      // P1 — subject-starter (breadth map) > variant/harder > review > practice kickoff
      const subjectKick = consumeSubjectStarter();
      const variantKick = subjectKick ? null : consumeVariantKickoff();
      const wrongKick = variantKick ? null : consumeWrongReviewKickoff();
      const kick = wrongKick ? null : consumePracticeKickoff();
      setSessionOpener(
        subjectKick
          ? {
              skillId: "explore",
              label: subjectKick.label,
              kind: "practice",
              line: `Let's peek at ${subjectKick.label} — one fresh question.`,
              kickoffOverride: subjectKick.starter,
            }
          : variantKick
            ? buildVariantKickoffOpener(variantKick)
            : wrongKick
              ? buildWrongReviewOpener(wrongKick)
              : kick
                ? buildPracticeKickoffOpener(kick)
                : buildSessionOpener(mem, accountId),
      );
    } else {
      setSessionOpener(null);
    }
  }, [ready, store, accountId, sessionId, messages.length, learningMemory]);

  // Esc closes mobile sidebar drawer
  useEffect(() => {
    if (!sidebarOpen) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setSidebarOpen(false);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [sidebarOpen]);

  const handleDismissBreakNudge = useCallback(() => {
    dismissBreakNudge();
    setBreakNudge(null);
  }, []);

  // V2 P0 — proactive review invite: "Not now" (off for the day) / accept.
  const handleDismissProactiveInvite = useCallback(() => {
    dismissProactiveToday(accountId);
    noteReviewStarted(accountId);
    setProactiveInvite(null);
  }, [accountId]);

  const handleAcceptProactiveInvite = useCallback(() => {
    if (!proactiveInvite) return;
    const kickoff = proactiveInvite.kickoff;
    noteReviewStarted(accountId);
    setProactiveInvite(null);
    void handleSend({ text: kickoff, attachments: [], source: "proactive" });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [accountId, proactiveInvite]);

  // V2 P1 — creation offer: "Not now" simply clears it.
  const handleDismissCreationOffer = useCallback(() => {
    setCreationOffer(null);
  }, []);

  const handleOpenCodeAgent = useCallback(() => { setAgentPanelOpen(true); setAgentPanelMinimized(false); }, []);

  const handleSwitchAccount = (id: string) => {
    if (id === accountId || busy) return;
    commitSessionFocus();
    // Prevent in-flight init photo vault from overwriting the new account's store
    accountIdRef.current = id;
    // Save current state
    if (store) saveConversations(store, accountId);
    if (learningMemory) {
      saveLearningMemory(learningMemory, accountId);
      void pushLearningMemoryToServer(learningMemory, accountId);
    }
    // Switch
    const updatedStore = switchAccount(id);
    const switchedAcct = getActiveAccount(updatedStore);
    setAccounts(updatedStore.accounts);
    setAccountId(id);
    setAccountName(switchedAcct.profile.name);
    // Reload all per-account data
    setVoiceEnabled(loadSpeakEnabled(id));
    voiceEnabledRef.current = loadSpeakEnabled(id);
    const vid = loadVoiceId(id);
    setVoiceId(vid);
    voiceIdRef.current = vid;
    setEngagement(loadEngagement(id));
    const mem = loadLearningMemory(id);
    setLearningMemory(mem);
    void hydrateLearningMemoryFromServer(id).then(setLearningMemory);
    // Reset chat to new account's conversations
    const nextStore = loadConversations(id);
    // Sync the refs in the same tick as accountIdRef — React's store state
    // and storeRef effect update asynchronously, so a periodic sync firing
    // right after the switch would read the previous account's store with
    // the new accountId and cross-contaminate localStorage / the server.
    storeRef.current = nextStore;
    setStore(nextStore);
    setError("");
    stopSpeakAll();
    if (nextStore.conversations.length > 0) {
      setUrlSession(nextStore.activeId, id);
    }
    // Background: hydrate new account's conversations from server, restore
    // photos from vault, and fetch any still-missing photos from server media.
    void (async () => {
      const merged = await hydrateFromServer(nextStore, id);
      const restored = await restoreStorePhotosFromVault(merged);
      const fetched = await fetchMissingPhotosFromServer(restored);
      // Upload local-only media that the server no longer has
      const { store: repaired } = await repairMissingMedia(fetched, id);
      const final = repaired !== fetched ? repaired : fetched;
      if (accountIdRef.current !== id) return;
      setStore(final);
      saveConversations(final, id);
      await ingestStorePhotos(final);
      void pushStoreToServer(final, id);
    })();
  };

  const startNewSession = () => {
    if (!store || busy) return;

    // Commit current focus time before switching sessions
    commitSessionFocus();

    // Generate a digest for the session we're leaving (if it has meaningful messages)
    const prevActive = getActiveConversation(store);
    const mem = learningMemory || loadLearningMemory(accountId);
    if (prevActive && prevActive.messages.length >= 2) {
      const digest = autoGenerateDigest(
        prevActive.messages.map((m) => ({
          role: m.role === "assistant" ? "assistant" : "user",
          content: m.content,
        })),
        prevActive.title,
      );
      if (digest) {
        const nextMem = appendDigestToMemory(mem, digest);
        setLearningMemory(nextMem);
        saveLearningMemory(nextMem, accountId);
        void pushLearningMemoryToServer(nextMem, accountId);
      }
    }

    // A2.h — shared session-close (practice offer, idempotent)
    let conversations = store.conversations;
    if (prevActive) {
      const closed = maybeCloseSession(prevActive, mem, accountId);
      if (closed.closed) {
        conversations = stampConversationInList(
          conversations,
          prevActive.sessionId,
          closed.conversation,
        );
      }
      if (closed.offer) {
        setPracticeOffer(closed.offer);
      }
    }

    const id = newSessionId();
    resetIdsRef.current.add(id);
    resetNextRef.current = true;
    const now = Date.now();
    // Drop other empty chats so the list stays tidy
    const kept = conversations.filter((c) => c.messages.length > 0);
    setStore({
      version: 3,
      activeId: id,
      conversations: [
        {
          sessionId: id,
          title: "New chat",
          messages: [],
          createdAt: now,
          updatedAt: now,
        },
        ...kept,
      ],
    });
    setError("");
    stopSpeakAll();
    setUrlSession(id, accountId);
    // V2 P1 — creation offer belongs to the conversation that produced it.
    setCreationOffer(null);

    // CA-3 — once/day opener on empty new chat (practice offer takes precedence in UI)
    const opener = buildSessionOpener(mem, accountId);
    setSessionOpener(opener);
    const digest = buildParentDailyDigest(mem);
    const dismissKey = `spark.dailyBlurbDismissed.${accountId}.${new Date().toISOString().slice(0, 10)}`;
    let dismissed = false;
    try {
      dismissed = sessionStorage.getItem(dismissKey) === "1";
    } catch {
      dismissed = false;
    }
    setDailyBlurb(
      !dismissed && digest && !digest.startsWith("Today: no skill")
        ? digest
        : null,
    );
  };

  // TED Challenge → homepage Q&A: consume one-shot kickoff after store is ready
  useEffect(() => {
    if (!ready || !store || tedKickoffHandledRef.current) return;
    tedKickoffHandledRef.current = true;
    const kick = consumeTedChallengeKickoff();
    if (!kick) {
      const resume = peekTedChallengeResume();
      if (resume) {
        setTedReturn({
          talkTitle: resume.talkTitle,
          nextQi: resume.qi,
          coherent: false,
        });
      }
      return;
    }
    setPracticeOffer(null);
    setSessionOpener(null);
    setTedReturn({
      talkTitle: kick.talkTitle,
      nextQi: kick.nextQi,
      coherent: false,
    });
    pendingTedKickoffRef.current = buildTedChallengeKickoffMessage(kick);
    if (messages.length > 0) {
      startNewSession();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- one-shot on ready
  }, [ready, store]);

  // Auto-send kickoff once the active chat is empty
  useEffect(() => {
    if (!ready || !store || !sessionId || busy) return;
    const text = pendingTedKickoffRef.current;
    if (!text || messages.length > 0) return;
    pendingTedKickoffRef.current = null;
    void handleSend({ text, attachments: [], source: "challenge" });
    // eslint-disable-next-line react-hooks/exhaustive-deps -- one-shot after new session
  }, [ready, store, sessionId, busy, messages.length]);

  // Strengthen return banner when tutor signals coherent reasoning
  useEffect(() => {
    if (!tedReturn || tedReturn.coherent) return;
    const lastAssistant = [...messages]
      .reverse()
      .find((m) => m.role === "assistant");
    if (lastAssistant && detectTedCoherenceSignal(lastAssistant.content)) {
      setTedReturn((prev) => (prev ? { ...prev, coherent: true } : null));
    }
  }, [messages, tedReturn]);

  const selectConversation = (id: string) => {
    if (!store || busy || id === store.activeId) return;
    commitSessionFocus();
    stopSpeakAll();
    const mem = learningMemory || loadLearningMemory(accountId);
    const leaving = getActiveConversation(store);
    let conversations = store.conversations;
    if (leaving && leaving.sessionId !== id) {
      const closed = maybeCloseSession(leaving, mem, accountId);
      if (closed.closed) {
        conversations = stampConversationInList(
          conversations,
          leaving.sessionId,
          closed.conversation,
        );
      }
      if (closed.offer) setPracticeOffer(closed.offer);
    }
    setStore({ ...store, activeId: id, conversations });
    setUrlSession(id, accountId);
    setError("");
    resetNextRef.current = resetIdsRef.current.has(id);
  };

  const deleteConversation = (id: string) => {
    if (!store || busy) return;
    const doomed = store.conversations.find((c) => c.sessionId === id);
    let conversations = store.conversations.filter((c) => c.sessionId !== id);
    let activeId = store.activeId;
    if (activeId === id) {
      if (conversations.length === 0) {
        const nid = newSessionId();
        resetIdsRef.current.add(nid);
        resetNextRef.current = true;
        const now = Date.now();
        conversations = [
          {
            sessionId: nid,
            title: "New chat",
            messages: [],
            createdAt: now,
            updatedAt: now,
          },
        ];
        activeId = nid;
      } else {
        activeId = [...conversations].sort(
          (a, b) => b.updatedAt - a.updatedAt,
        )[0]!.sessionId;
        resetNextRef.current = resetIdsRef.current.has(activeId);
      }
    }
    resetIdsRef.current.delete(id);
    stopSpeakAll();
    const nextStore = { version: 3 as const, activeId, conversations };
    setStore(nextStore);
    setUrlSession(activeId, accountId);
    setError("");
    // Drop server JSON + data/media, and local IndexedDB photos for this chat
    void deleteServerChat(id, accountId);
    if (doomed) {
      void deletePhotosFromVault(vaultIdsFromConversation(doomed));
    }
    void pruneVaultToStore(nextStore);
  };

  const handleSend = async (payload: {
    text: string;
    attachments: ClientAttachment[];
    quote?: ChatQuote;
    /** V2 attribution — the learning mechanism that started this turn. */
    source?: LearningSource;
  }) => {
    if (busy || !store || !sessionId) return;

    // Start focus timer on first message of the session
    startSessionTimer();

    // P0 — flow signal: how long the student took to answer the last question.
    // Captured at send time (their answer latency), used after outcome classify.
    const answerLatencyMs = Date.now() - lastAssistantAtRef.current;

    // UX-RPT.7 / P0 — narrow local fast-path (no Agent): arithmetic facts
    // first, then unit/formula/power-table facts (report §8.2).
    const recall =
      payload.attachments.length === 0 ? tryLocalRecall(payload.text) : null;
    const fact =
      payload.attachments.length === 0 ? tryLocalFacts(payload.text) : null;
    const localHit = recall ?? fact;
    if (localHit) {
      setBusy(true);
      setError("");
      setAgentStatus("");
      if (sessionOpener) {
        markOpenerShown(accountId);
        setSessionOpener(null);
      }
      const userMsg: ChatMessage = {
        id: messageId(),
        role: "user",
        content: payload.text,
        quote: payload.quote ?? undefined,
        createdAt: Date.now(),
      };
      const assistantMsg: ChatMessage = {
        id: messageId(),
        role: "assistant",
        content: localHit.reply,
        createdAt: Date.now(),
      };
      const nextMessages = [...messages, userMsg, assistantMsg];
      setStore((prev) =>
        prev
          ? upsertActive(
              { ...prev, activeId: sessionId },
              { messages: nextMessages },
            )
          : prev,
      );
      const streak = noteEmotionOutcome("win");
      setEmotionLine(emotionUiLine(streak));
      lastAssistantAtRef.current = Date.now();
      setBusy(false);
      return;
    }

    setBusy(true);
    setError("");
    const hasMedia = payload.attachments.length > 0;
    const waitStartedAt = Date.now();
    setAgentStatus(initialWaitStatus({ hasMedia }));
    if (waitPhaseTimerRef.current != null) {
      window.clearInterval(waitPhaseTimerRef.current);
      waitPhaseTimerRef.current = null;
    }
    waitPhaseTimerRef.current = window.setInterval(() => {
      setAgentStatus((cur) => {
        if (!isGenericWaitStatus(cur)) return cur;
        return waitStatusAt({ hasMedia }, Date.now() - waitStartedAt);
      });
    }, 1000);

    // B1.h — any student turn (homework photo/text) yields the ZPD opener for the day
    if (sessionOpener) {
      markOpenerShown(accountId);
      setSessionOpener(null);
    }

    const needReset =
      resetNextRef.current || resetIdsRef.current.has(sessionId);
    const history = buildHistoryPreview(messages);
    const shouldSpeak = voiceEnabledRef.current;

    // Vault attachments immediately so history stays viewable / downloadable
    for (const a of payload.attachments) {
      if (a.dataUrl) {
        void putPhotoInVault({
          id: a.id,
          dataUrl: a.dataUrl,
          mimeType: a.mimeType,
          name: a.name,
        });
      }
    }
    const userMsg: ChatMessage = {
      id: messageId(),
      role: "user",
      content: payload.text,
      quote: payload.quote ?? undefined,
      attachments: payload.attachments.map((a) => ({
        id: a.id,
        name: a.name,
        mimeType: a.mimeType,
        kind: a.kind,
        dataUrl: a.dataUrl,
      })),
      createdAt: Date.now(),
    };
    const assistantId = messageId();
    const nextMessages: ChatMessage[] = [
      ...messages,
      userMsg,
      { id: assistantId, role: "assistant", content: "", createdAt: Date.now() },
    ];

    setStore((prev) =>
      prev
        ? upsertActive(
            { ...prev, activeId: sessionId },
            { messages: nextMessages },
          )
        : prev,
    );

    if (shouldSpeak) {
      setSpeakingMessageId(null);
      speakApiRef.current?.begin();
    }

    try {
      const profile = loadStudentProfile();
      const mem = learningMemory || loadLearningMemory(accountId);
      const eng = engagement || loadEngagement(accountId);
      const recentTitles = store.conversations
        .filter((c) => c.sessionId !== sessionId && c.messages.length > 0)
        .sort((a, b) => b.updatedAt - a.updatedAt)
        .slice(0, 5)
        .map((c) => c.title)
        .filter((t) => t && t !== "New chat");
      const coachNote = [
        emotionPromptLines().filter(Boolean).join("\n"),
        flowAdvicePromptNote(flowAdviceRef.current),
      ]
        .filter(Boolean)
        .join("\n") || undefined;

      const wireQuote = payload.quote
        ? resolveQuoteForSend(payload.quote, messages)
        : undefined;

      const full = await consumeChatStream(
        {
          sessionId,
          message: payload.text,
          reset: needReset,
          quote: wireQuote,
          history: needReset ? undefined : history,
          recentTitles,
          studentProfile: profile,
          learningMemory: serializeLearningMemoryForChat(mem),
          engagement: engagementForPrompt(eng),
          voiceId: voiceIdRef.current,
          replyLanguage: resolveReplyLanguage(
            voiceIdRef.current,
            payload.text,
            profile.preferredChinese,
          ),
          checkMode: checkModeRef.current === true,
          coachNote,
          attachments: payload.attachments.map((a) => ({
            name: a.name,
            mimeType: a.mimeType,
            kind: a.kind,
            data: a.data,
            textContent: a.textContent,
          })),
        },
        // rAF-batched onDelta: group SSE deltas into one React state update
        // per animation frame to cut re-renders from 100+/sec to 60/sec
        // and eliminate screen flicker during streaming.
        (() => {
          let pendingDelta = "";
          let pendingRafId: number | undefined;
          return (delta: string) => {
            if (waitPhaseTimerRef.current != null) {
              window.clearInterval(waitPhaseTimerRef.current);
              waitPhaseTimerRef.current = null;
            }
            setAgentStatus("");
            // Feed every raw delta to TTS immediately for fluid speech
            if (shouldSpeak) {
              speakApiRef.current?.push(delta);
            }
            pendingDelta += delta;
            if (pendingRafId !== undefined) return; // already scheduled
            pendingRafId = requestAnimationFrame(() => {
              pendingRafId = undefined;
              const batch = pendingDelta;
              pendingDelta = "";
              if (!batch) return;
              setStore((prev) => {
                if (!prev) return prev;
                const cur = getActiveConversation(prev);
                if (cur.sessionId !== sessionId) return prev;
                const msgs = cur.messages.map((m) =>
                  m.id === assistantId
                    ? { ...m, content: m.content + batch }
                    : m,
                );
                return upsertActive(prev, { messages: msgs });
              });
            });
          };
        })(),
        (status) => {
          setAgentStatus((cur) => {
            if (!status) return cur;
            // Real tool labels win; timed wait phases own generic Thinking…
            if (!isGenericWaitStatus(status)) return status;
            if (cur && !isGenericWaitStatus(cur)) return cur;
            return cur || status;
          });
        },
        (text) => {
          // Replace glued streaming text with the corrected final reply
          setStore((prev) => {
            if (!prev) return prev;
            const cur = getActiveConversation(prev);
            if (cur.sessionId !== sessionId) return prev;
            const msgs = cur.messages.map((m) =>
              m.id === assistantId ? { ...m, content: text } : m,
            );
            return upsertActive(prev, { messages: msgs });
          });
        },
      );
      resetNextRef.current = false;
      resetIdsRef.current.delete(sessionId);
      lastAssistantAtRef.current = Date.now();
      setEngagement(recordLearningTurn(undefined, accountId));
      // V2 P1 — BKT prior tier (report §9.3.1): high-prior students get more
      // aggressive learning parameters and a more eager auto-advance trigger.
      const priorTier = detectPriorTier(profile, mem);
      let nextMem = recordLearningTurnMemory(mem, {
        userText: payload.text,
        assistantText: full,
        chatTitle: active?.title || titleFromMessages(messages),
        priorTier,
        source: payload.source,
      });
      const suggestion = autoAdvanceCheck(nextMem, profile.gradeBand, priorTier);
      if (suggestion && !nextMem.advanceSuggestion) {
        nextMem = { ...nextMem, advanceSuggestion: suggestion };
      }
      // CA-6 — merge misconception fence into skill hits
      const mcHit = parseMisconceptionFence(full);
      if (mcHit) {
        const skillGuess =
          inferSkillsFromText([payload.text, full].join("\n"))[0]?.id;
        nextMem = applyMisconceptionToMemory(nextMem, skillGuess, mcHit);
        saveLearningMemory(nextMem, accountId);
      }
      // CA-5 — parse scratch diagnosis (drives prompt via next turns; strip in UI)
      parseScratchDiagnosisFence(full);
      setLearningMemory(nextMem);
      syncProfileFromSkills(profile, nextMem);
      void pushLearningMemoryToServer(nextMem, accountId);
      // P2 — short-cycle weekly goal: count skills newly mastered this week.
      reconcileWeeklyGoal(accountId, nextMem);

      const outcome = classifyTurnOutcome(payload.text, full);
      // P0 — in-session flow: record answer latency, get step-up/step-down advice
      const flowAdvice = recordFlowTurn(outcome, { latencyMs: answerLatencyMs });
      // V2 P0 — surface the "growth moment" line and remember the advice for
      // the next turn's prompt (report §9.2.1).
      flowAdviceRef.current = flowAdvice;
      setFlowMoment(flowAdviceLabel(flowAdvice));
      // V2 P1 — interest → creation loop (report §9.1.3): when the child gets
      // a turn right AND sounds enthusiastic, offer a mini-creation card.
      if (
        outcome === "correct" &&
        likesTopicSignal(payload.text, full) &&
        !creationOffer
      ) {
        const last = recentInterests(accountId, 1)[0];
        if (last) {
          setCreationOffer({
            topicLabel: last.label,
            createdAt: Date.now(),
          });
        }
      }
      // P1 — auto difficulty ramp: fast correct streaks climb faster; slow or
      // wrong streaks drop back (only while a challenge session is active).
      recordChallengeOutcome(accountId, outcome, {
        fast: flowAdvice === "step-up",
        slow: flowAdvice === "step-down",
      });
      // P1 — wrong-answer book: log incorrect turns with the question asked.
      if (outcome === "incorrect") {
        const lastAssistant = [...messages]
          .reverse()
          .find((m) => m.role === "assistant");
        const inferred = skillLabelForText(
          [lastAssistant?.content || "", payload.text].join("\n"),
        );
        addWrongAnswer(accountId, {
          skillId: inferred.skillId,
          skillLabel: inferred.skillLabel,
          question: lastAssistant?.content || "",
          studentAnswer: payload.text,
          assistantText: full,
        });
        // V2 P0 — proactive outreach: remember this wrong answer is pending a
        // follow-up review (surfaced as a non-blocking invite later).
        noteWrongAnswerAt(accountId);
      }
      // V2 P0 — if the child just started a wrong-review/variant kickoff, that
      // counts as the follow-up: no proactive invite for this wrong answer.
      if (isWrongReviewKickoff(payload.text)) {
        noteReviewStarted(accountId);
      }
      const emotionKind =
        outcome === "correct"
          ? "win"
          : outcome === "incorrect"
            ? "struggle"
            : "neutral";
      const streak = noteEmotionOutcome(emotionKind);
      setEmotionLine(emotionUiLine(streak));

      if (shouldSpeak) {
        speakApiRef.current?.finish(full);
      }
      // Always pin the merged final text so a streamed diagram cannot vanish
      // after done/onReplace/storage races. CA-1: also merge worksheet plan.
      // CA-8: collapse same-diagramId revisions inside the assistant message.
      const plan = parseWorksheetPlanFence(full);
      const pinned = full.trim()
        ? collapseSameDiagramImages(full)
        : "";
      setStore((prev) => {
        if (!prev) return prev;
        const cur = getActiveConversation(prev);
        if (cur.sessionId !== sessionId) return prev;
        const msgs = cur.messages.map((m) =>
          m.id === assistantId
            ? {
                ...m,
                content: pinned || m.content || "(empty reply)",
              }
            : m,
        );
        const merged = plan
          ? mergeWorksheetPlan(cur.worksheetPlan, plan)
          : cur.worksheetPlan;
        return upsertActive(prev, {
          messages: msgs,
          worksheetPlan: merged ?? undefined,
        });
      });
    } catch (err) {
      const raw = err instanceof Error ? err.message : "Send failed";
      const msg = softSendErrorLine(raw);
      setError(msg);
      if (raw.includes("CURSOR_API_KEY") || raw.includes("API Key")) {
        setKeyMissing(true);
      }
      stopSpeakAll();
      setStore((prev) => {
        if (!prev) return prev;
        const cur = getActiveConversation(prev);
        if (cur.sessionId !== sessionId) return prev;
        const msgs = cur.messages.map((m) =>
          m.id === assistantId
            ? {
                ...m,
                content: m.content || `Sorry — something went wrong: ${msg}`,
              }
            : m,
        );
        return upsertActive(prev, { messages: msgs });
      });
    } finally {
      if (waitPhaseTimerRef.current != null) {
        window.clearInterval(waitPhaseTimerRef.current);
        waitPhaseTimerRef.current = null;
      }
      setBusy(false);
      setAgentStatus("");
      // Persist promptly when the turn ends
      window.setTimeout(() => {
        setStore((prev) => (prev ? { ...prev } : prev));
      }, 0);
    }
  };

  return {
    ready, store, busy, error, setError, agentStatus, keyMissing,
    voiceEnabled, setVoiceEnabled, voiceId, setVoiceId, voiceIdRef,
    sidebarOpen, setSidebarOpen, desktopSidebarOpen, setDesktopSidebarOpen, isLg,
    agentPanelOpen, setAgentPanelOpen, agentPanelMinimized, setAgentPanelMinimized,
    engagement, learningMemory, practiceOffer, sessionOpener, tedReturn, setTedReturn,
    dailyBlurb, setDailyBlurb, emotionLine, setEmotionLine, accountName, accountId, accounts,
    ttsSpeaking, setTtsSpeaking, speakingMessageId, setSpeakingMessageId, checkMode, setCheckMode,
    scrollerRef, composerApiRef, speakApiRef, messagesOpen, setMessagesOpen,
    active, sessionId, messages,
    handleSwitchAccount, startNewSession, selectConversation, deleteConversation, handleSend,
    setSpeakApi, stopSpeakAll, handleOpenCodeAgent, setKeyMissing,
    setPracticeOffer, setSessionOpener, setStore,
    breakNudge, handleDismissBreakNudge,
    proactiveInvite, handleDismissProactiveInvite, handleAcceptProactiveInvite,
    flowMoment, setFlowMoment,
    creationOffer, handleDismissCreationOffer, creationOfferLine,
  };
}
