"use client";
import type { ConsoleMessage } from "@/lib/types";
type Props={messages:ConsoleMessage[];streaming?:boolean;studentName?:string};
export function ConsoleThread({messages,streaming,studentName}:Props){
  const label = studentName || "";
  if(messages.length===0&&!streaming)return <div className="flex flex-col items-center gap-3 px-4 py-16 text-center"><span className="text-4xl">🛠</span><h2 className="text-lg font-semibold text-[var(--ink)]">{label ? `Hi ${label}! I can help improve Spark.` : "Hi! I can help improve Spark."}</h2><p className="max-w-md text-sm text-[var(--ink-muted)]">Tell me what to change and I&apos;ll read the code, make edits, and run tests.</p><p className="text-sm text-[var(--ink-muted)]">Try: <span className="font-medium text-[var(--teal)]">Make the voice slower</span></p></div>;
  return <div className="flex flex-col gap-3 px-4 py-4">{messages.map(m=><B key={m.id} m={m} name={label}/>)}{streaming?<div className="flex items-center gap-2 px-4 py-3"><div className="flex gap-1">{[0,200,400].map((d,i)=><div key={i} className="h-2 w-2 animate-pulse rounded-full bg-[var(--teal)]" style={{animationDelay:d+"ms"}}/>)}</div><span className="text-sm text-[var(--ink-muted)]">Builder is working…</span></div>:null}</div>;
}
function B({m,name}:{m:ConsoleMessage;name:string}){if(m.role==="system")return <div className="rounded-xl bg-[var(--mist)]/50 px-4 py-2 text-center text-sm text-[var(--ink-muted)]">{m.content}</div>;const u=m.role==="user";return <div className={"flex flex-col gap-1"+(u?" items-end":" items-start")}><span className="text-[11px] font-medium text-[var(--ink-muted)]">{u?(name||"Student"):"🛠 Spark Builder"}</span><div className={"max-w-[85%] rounded-2xl px-4 py-3"+(u?" bg-[var(--teal)]/10 text-[var(--ink)]":" bg-[var(--mist)] text-[var(--ink)]")}>{m.attachments&&m.attachments.length>0?<div className="mb-1.5 flex flex-wrap gap-1">{m.attachments.map((a,i)=><span key={`${a.name}-${i}`} className="inline-flex max-w-[160px] items-center gap-1 rounded-full bg-[var(--surface-muted)] px-2 py-0.5 text-[11px] text-[var(--ink-muted)]">{a.kind==="image"?"🖼":"📄"}<span className="truncate">{a.name}</span></span>)}</div>:null}<p className="whitespace-pre-wrap break-words text-[15px]">{m.content}</p></div></div>}
