"use client";
import { useMemo, useState } from "react";
import type { DiffBlock } from "@/lib/types";
type Props={diff:DiffBlock;compactLines?:number;onExpand?:()=>void};
function color(l:string):"add"|"remove"|"context"|"header"{if(l.startsWith("+++")||l.startsWith("---")||l.startsWith("@@"))return"header";if(l.startsWith("+"))return"add";if(l.startsWith("-"))return"remove";return"context"}
export function DiffViewer({diff,compactLines,onExpand}:Props){
  const[exp,setExp]=useState(!compactLines);
  const lines=useMemo(()=>{const all=diff.hunks.split("\n");if(compactLines&&!exp)return all.slice(0,compactLines*2);return all},[diff.hunks,compactLines,exp]);
  const more=compactLines&&diff.hunks.split("\n").length>lines.length;
  return <div className="my-2 overflow-hidden rounded-lg border border-[var(--line)]"><div className="flex items-center gap-2 bg-[var(--mist)]/80 px-3 py-2 text-xs font-medium text-[var(--ink)]"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14,2 14,8 20,8"/></svg><span className="flex-1">{diff.filepath}</span><span className="text-[var(--teal)]">+{diff.added}</span><span className="text-[var(--coral)]">-{diff.removed}</span></div><div className="overflow-x-auto bg-[var(--diff-code-bg)] font-mono text-[13px] leading-relaxed">{lines.map((l:string,i:number)=>{const c=color(l);return <div key={i} className={"flex"+(c==="add"?" bg-[var(--diff-add-bg)]":c==="remove"?" bg-[var(--diff-remove-bg)]":c==="header"?" bg-[var(--mist)]/40 text-[var(--ink-muted)]":"")}><span className="mr-2 inline-block w-8 shrink-0 select-none text-right text-[11px] text-[var(--ink-muted)]/50">{i+1}</span><span className={c==="add"?"text-[var(--diff-add)]":c==="remove"?"text-[var(--diff-remove)]":c==="header"?"text-[var(--ink-muted)]":"text-[var(--ink)]"}>{c!=="header"?<span className="mr-1 select-none font-bold">{c==="add"?"+":c==="remove"?"-":" "}</span>:null}{c!=="header"?l.slice(1):l}</span></div>})}{more?<button type="button" onClick={()=>{setExp(true);onExpand?.()}} className="flex w-full items-center justify-center gap-1 border-t border-[var(--line)]/30 py-2 text-xs font-medium text-[var(--ink-muted)] hover:bg-[var(--mist)]/50">{diff.hunks.split("\n").length-lines.length} more lines</button>:null}</div></div>;
}
