"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ChatThread } from "./ChatThread";
import { Composer } from "./Composer";
import { HistorySidebar } from "./HistorySidebar";
import { MiniConsoleShell } from "./MiniConsoleShell";
import { AgentConsolePanel } from "./AgentConsolePanel";
import { SetupPanel } from "./SetupPanel";
import {
  loadSpeakEnabled,
  loadVoiceId,
  resolveReplyLanguage,
  type TutorVoiceId,
} from "@/lib/voices";
import {
  getActiveConversation,
  loadConversations,
  MAX_MESSAGES_PER_CHAT,
  newSessionId,
  saveConversations,
  sessionIdFromUrl,
  setUrlSession,
  titleFromMessages,
} from "@/lib/storage";
import {
  deleteServerChat,
  hydrateFromServer,
  pushStoreToServer,
} from "@/lib/history-sync";
import {
  engagementForPrompt,
  engagementSummary,
  loadEngagement,
  recordLearningTurn,
  type EngagementState,
} from "@/lib/engagement";
import {
  loadStudentProfile,
  syncProfileFromSkills,
} from "@/lib/student-profile";
import {
  hydrateLearningMemoryFromServer,
  learningMemorySummary,
  loadLearningMemory,
  pushLearningMemoryToServer,
  recordLearningTurnMemory,
  saveLearningMemory,
  serializeLearningMemoryForChat,
  autoGenerateDigest,
  appendDigestToMemory,
  type LearningMemory,
} from "@/lib/learning-memory";
import {
  deletePhotosFromVault,
  ingestStorePhotos,
  pruneVaultToStore,
  putPhotoInVault,
  restoreStorePhotosFromVault,
  vaultIdsFromConversation,
} from "@/lib/photo-vault";
import type { ClientAttachment } from "@/lib/file-payload";
import type {
  ChatMessage,
  ConversationRecord,
  ConversationsStore,
  HistoryTurn,
} from "@/lib/types";
import type { SpeakStreamApi } from "./VoiceControls";
import { preferCompleteTutorText, hasTutorDiagram } from "@/lib/tutor-text-filter";

function messageId() {
  return `m_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

function buildHistoryPreview(messages: ChatMessage[]): HistoryTurn[] {
  return messages
    .filter((m) => m.role === "user" || m.role === "assistant")
    .filter((m) => m.content.trim())
    .slice(-8)
    .map((m) => ({
      role: m.role as "user" | "assistant",
      content: m.content.replace(/\s+/g, " ").trim().slice(0, 500),
    }));
}

async function consumeChatStream(
  body: unknown,
  onDelta: (text: string) => void,
  onStatus?: (status: string) => void,
  onReplace?: (text: string) => void,
): Promise<string> {
  const payload = JSON.stringify(body);

  const readStream = async (res: Response): Promise<string> => {
    if (!res.body) throw new Error(`Request failed (${res.status})`);
    const reader = res.body.getReader();
    const decoder = new TextDecoder();
    let buffer = "";
    let full = "";
    let streamError = "";

    const paint = () =>
      new Promise<void>((resolve) => {
        if (typeof requestAnimationFrame === "function") {
          requestAnimationFrame(() => resolve());
        } else {
          setTimeout(resolve, 0);
        }
      });

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      const parts = buffer.split("\n\n");
      buffer = parts.pop() ?? "";

      let gotDelta = false;
      for (const part of parts) {
        const lines = part.split("\n");
        let event = "message";
        let dataLine = "";
        for (const line of lines) {
          if (line.startsWith("event:")) event = line.slice(6).trim();
          if (line.startsWith("data:")) dataLine += line.slice(5).trim();
        }
        if (!dataLine) continue;
        const data = JSON.parse(dataLine) as {
          text?: string;
          error?: string;
          status?: string;
        };
        if (event === "delta" && data.text) {
          full += data.text;
          onDelta(data.text);
          gotDelta = true;
        }
        if (event === "status" && data.status) {
          onStatus?.(data.status);
        }
        if (event === "error" && data.error) {
          streamError = data.error;
        }
        // Always prefer the server's final text — streaming deltas often glue
        // English words ("Hello" + "world" → "Helloworld" if spaces were dropped).
        // Never replace a streamed diagram with a diagram-less final.
        if (event === "done" && data.text) {
          let preferred = preferCompleteTutorText(full, data.text);
          if (hasTutorDiagram(full) && !hasTutorDiagram(preferred)) {
            preferred = full;
          }
          if (!full) {
            full = preferred;
            onDelta(preferred);
            gotDelta = true;
          } else if (preferred !== full) {
            full = preferred;
            onReplace?.(preferred);
            gotDelta = true;
          }
        }
      }
      // Let React paint between SSE chunks (critical on iPad)
      if (gotDelta) await paint();
    }

    if (streamError) throw new Error(streamError);
    return full;
  };

  for (let attempt = 0; attempt < 2; attempt += 1) {
    const res = await fetch("/api/chat", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: payload,
    });

    if (res.ok) {
      return readStream(res);
    }

    const data = (await res.json().catch(() => null)) as {
      error?: string;
    } | null;
    const msg = data?.error || `Request failed (${res.status})`;
    const retryable =
      attempt === 0 &&
      (res.status === 400 || res.status === 502 || res.status === 503) &&
      (!data?.error || /invalid json|bad request/i.test(msg));
    if (retryable) {
      await new Promise((r) => setTimeout(r, 350));
      continue;
    }
    throw new Error(msg);
  }

  throw new Error("Request failed");
}

function upsertActive(
  store: ConversationsStore,
  patch: Partial<ConversationRecord> & { messages?: ChatMessage[] },
): ConversationsStore {
  const now = Date.now();
  const idx = store.conversations.findIndex(
    (c) => c.sessionId === store.activeId,
  );
  const prev =
    idx >= 0
      ? store.conversations[idx]!
      : {
          sessionId: store.activeId,
          title: "New chat",
          messages: [],
          createdAt: now,
          updatedAt: now,
        };

  let messages = patch.messages ?? prev.messages;
  if (messages.length > MAX_MESSAGES_PER_CHAT) {
    messages = messages.slice(-MAX_MESSAGES_PER_CHAT);
  }

  const next: ConversationRecord = {
    ...prev,
    ...patch,
    messages,
    title: titleFromMessages(messages),
    updatedAt: now,
  };

  const conversations = [...store.conversations];
  if (idx >= 0) conversations[idx] = next;
  else conversations.unshift(next);

  return { ...store, conversations };
}

export function TutorShell() {
  const [ready, setReady] = useState(false);
  const [store, setStore] = useState<ConversationsStore | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [agentStatus, setAgentStatus] = useState("");
  const [keyMissing, setKeyMissing] = useState(false);
  const [voiceEnabled, setVoiceEnabled] = useState(true);
  const [voiceId, setVoiceId] = useState<TutorVoiceId>("auto");
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [miniConsoleOpen, setMiniConsoleOpen] = useState(false);
  const [agentPanelOpen, setAgentPanelOpen] = useState(false);
  const [engagement, setEngagement] = useState<EngagementState | null>(null);
  const [learningMemory, setLearningMemory] = useState<LearningMemory | null>(
    null,
  );
  const scrollerRef = useRef<HTMLDivElement>(null);
  const resetNextRef = useRef(false);
  /** sessionIds that need a fresh Cursor agent on next send */
  const resetIdsRef = useRef<Set<string>>(new Set());
  const speakApiRef = useRef<SpeakStreamApi | null>(null);
  const saveTimerRef = useRef<number | null>(null);
  const voiceEnabledRef = useRef(true);
  const voiceIdRef = useRef<TutorVoiceId>("auto");

  useEffect(() => {
    const enabled = loadSpeakEnabled();
    setVoiceEnabled(enabled);
    voiceEnabledRef.current = enabled;
    const vid = loadVoiceId();
    setVoiceId(vid);
    voiceIdRef.current = vid;
    setEngagement(loadEngagement());
    setLearningMemory(loadLearningMemory());
    void hydrateLearningMemoryFromServer().then(setLearningMemory);
  }, []);

  useEffect(() => {
    voiceEnabledRef.current = voiceEnabled;
  }, [voiceEnabled]);

  useEffect(() => {
    voiceIdRef.current = voiceId;
  }, [voiceId]);

  const setSpeakApi = useCallback((api: SpeakStreamApi | null) => {
    speakApiRef.current = api;
  }, []);

  useEffect(() => {
    const loaded = loadConversations();
    setStore(loaded);
    setReady(true);

    // 🔗 Zero-login: resolve ?session= URL param → select that conversation
    const urlSession = sessionIdFromUrl();
    if (urlSession && urlSession.length > 4) {
      const exists = loaded.conversations.some((c) => c.sessionId === urlSession);
      if (exists && loaded.activeId !== urlSession) {
        setStore({ ...loaded, activeId: urlSession });
      }
    }

    // Keep homework photos in IndexedDB, then merge server history, then
    // restore any photos the server JSON no longer carries as base64.
    void (async () => {
      await ingestStorePhotos(loaded);
      const merged = await hydrateFromServer(loaded);
      const restored = await restoreStorePhotosFromVault(merged);
      await ingestStorePhotos(restored);
      await pruneVaultToStore(restored);
      setStore(restored);
      saveConversations(restored);
      const withMedia = await pushStoreToServer(restored);
      if (withMedia !== restored) {
        setStore(withMedia);
        saveConversations(withMedia);
      }
    })();

    fetch("/api/setup")
      .then(async (r) => {
        const data = (await r.json()) as { configured?: boolean };
        // 仅在明确未配置时才弹出输入；网络失败不挡小孩使用（服务端有默认 Key）
        setKeyMissing(data.configured === false);
      })
      .catch(() => setKeyMissing(false));
  }, []);

  // Debounce localStorage + server sync while streaming — sync writes freeze the UI on iPad
  useEffect(() => {
    if (!ready || !store) return;
    if (saveTimerRef.current) window.clearTimeout(saveTimerRef.current);
    const delay = busy ? 1500 : 280;
    saveTimerRef.current = window.setTimeout(() => {
      saveConversations(store);
      if (!busy) {
        void (async () => {
          await ingestStorePhotos(store);
          const withMedia = await pushStoreToServer(store);
          if (withMedia !== store) {
            setStore(withMedia);
          }
        })();
      }
    }, delay);
    return () => {
      if (saveTimerRef.current) window.clearTimeout(saveTimerRef.current);
    };
  }, [ready, store, busy]);

  const active = useMemo(
    () => (store ? getActiveConversation(store) : null),
    [store],
  );
  const sessionId = active?.sessionId ?? "";
  const messages = active?.messages ?? [];

  useEffect(() => {
    const el = scrollerRef.current;
    if (!el) return;
    el.scrollTop = el.scrollHeight;
  }, [messages, busy]);

  // Esc closes sidebar
  useEffect(() => {
    if (!sidebarOpen) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setSidebarOpen(false);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [sidebarOpen]);

  const handleOpenMiniConsole = useCallback(() => { setMiniConsoleOpen(true); }, []);
  const handleOpenCodeAgent = useCallback(() => { setAgentPanelOpen(true); }, []);
  const handleOpenFullConsole = useCallback(() => { setMiniConsoleOpen(false); window.location.href = "/console"; }, []);

  const startNewSession = () => {
    if (!store || busy) return;

    // Generate a digest for the session we're leaving (if it has meaningful messages)
    const prevActive = getActiveConversation(store);
    if (prevActive && prevActive.messages.length >= 2) {
      const mem = learningMemory || loadLearningMemory();
      const digest = autoGenerateDigest(
        prevActive.messages.map((m) => ({
          role: m.role === "assistant" ? "assistant" : "user",
          content: m.content,
        })),
        prevActive.title,
      );
      if (digest) {
        const nextMem = appendDigestToMemory(mem, digest);
        setLearningMemory(nextMem);
        saveLearningMemory(nextMem);
        void pushLearningMemoryToServer(nextMem);
      }
    }

    const id = newSessionId();
    resetIdsRef.current.add(id);
    resetNextRef.current = true;
    const now = Date.now();
    // Drop other empty chats so the list stays tidy
    const kept = store.conversations.filter((c) => c.messages.length > 0);
    setStore({
      version: 3,
      activeId: id,
      conversations: [
        {
          sessionId: id,
          title: "New chat",
          messages: [],
          createdAt: now,
          updatedAt: now,
        },
        ...kept,
      ],
    });
    setError("");
    speakApiRef.current?.stop();
    setUrlSession(id);
  };

  const selectConversation = (id: string) => {
    if (!store || busy || id === store.activeId) return;
    speakApiRef.current?.stop();
    setStore({ ...store, activeId: id });
    setUrlSession(id);
    setError("");
    resetNextRef.current = resetIdsRef.current.has(id);
  };

  const deleteConversation = (id: string) => {
    if (!store || busy) return;
    const doomed = store.conversations.find((c) => c.sessionId === id);
    let conversations = store.conversations.filter((c) => c.sessionId !== id);
    let activeId = store.activeId;
    if (activeId === id) {
      if (conversations.length === 0) {
        const nid = newSessionId();
        resetIdsRef.current.add(nid);
        resetNextRef.current = true;
        const now = Date.now();
        conversations = [
          {
            sessionId: nid,
            title: "New chat",
            messages: [],
            createdAt: now,
            updatedAt: now,
          },
        ];
        activeId = nid;
      } else {
        activeId = [...conversations].sort(
          (a, b) => b.updatedAt - a.updatedAt,
        )[0]!.sessionId;
        resetNextRef.current = resetIdsRef.current.has(activeId);
      }
    }
    resetIdsRef.current.delete(id);
    speakApiRef.current?.stop();
    const nextStore = { version: 3 as const, activeId, conversations };
    setStore(nextStore);
    setError("");
    // Drop server JSON + data/media, and local IndexedDB photos for this chat
    void deleteServerChat(id);
    if (doomed) {
      void deletePhotosFromVault(vaultIdsFromConversation(doomed));
    }
    void pruneVaultToStore(nextStore);
  };

  const handleSend = async (payload: {
    text: string;
    attachments: ClientAttachment[];
  }) => {
    if (busy || !store || !sessionId) return;
    setBusy(true);
    setError("");
    setAgentStatus("Thinking…");

    const needReset =
      resetNextRef.current || resetIdsRef.current.has(sessionId);
    const history = buildHistoryPreview(messages);
    const shouldSpeak = voiceEnabledRef.current;

    // Vault attachments immediately so history stays viewable / downloadable
    for (const a of payload.attachments) {
      if (a.dataUrl) {
        void putPhotoInVault({
          id: a.id,
          dataUrl: a.dataUrl,
          mimeType: a.mimeType,
          name: a.name,
        });
      }
    }
    const userMsg: ChatMessage = {
      id: messageId(),
      role: "user",
      content: payload.text,
      attachments: payload.attachments.map((a) => ({
        id: a.id,
        name: a.name,
        mimeType: a.mimeType,
        kind: a.kind,
        dataUrl: a.dataUrl,
      })),
      createdAt: Date.now(),
    };
    const assistantId = messageId();
    const nextMessages: ChatMessage[] = [
      ...messages,
      userMsg,
      { id: assistantId, role: "assistant", content: "", createdAt: Date.now() },
    ];

    setStore((prev) =>
      prev
        ? upsertActive(
            { ...prev, activeId: sessionId },
            { messages: nextMessages },
          )
        : prev,
    );

    if (shouldSpeak) {
      speakApiRef.current?.begin();
    }

    try {
      const profile = loadStudentProfile();
      const mem = learningMemory || loadLearningMemory();
      const eng = engagement || loadEngagement();
      const recentTitles = store.conversations
        .filter((c) => c.sessionId !== sessionId && c.messages.length > 0)
        .sort((a, b) => b.updatedAt - a.updatedAt)
        .slice(0, 5)
        .map((c) => c.title)
        .filter((t) => t && t !== "New chat");

      const full = await consumeChatStream(
        {
          sessionId,
          message: payload.text,
          reset: needReset,
          history: needReset ? undefined : history,
          recentTitles,
          learningMemory: serializeLearningMemoryForChat(mem),
          engagement: engagementForPrompt(eng),
          voiceId: voiceIdRef.current,
          replyLanguage: resolveReplyLanguage(
            voiceIdRef.current,
            payload.text,
            profile.preferredChinese,
          ),
          attachments: payload.attachments.map((a) => ({
            name: a.name,
            mimeType: a.mimeType,
            kind: a.kind,
            data: a.data,
            textContent: a.textContent,
          })),
        },
        (delta) => {
          setAgentStatus("");
          // Paint text immediately as SSE chunks arrive
          setStore((prev) => {
            if (!prev) return prev;
            const cur = getActiveConversation(prev);
            if (cur.sessionId !== sessionId) return prev;
            const msgs = cur.messages.map((m) =>
              m.id === assistantId ? { ...m, content: m.content + delta } : m,
            );
            return upsertActive(prev, { messages: msgs });
          });
          if (shouldSpeak) {
            speakApiRef.current?.push(delta);
          }
        },
        (status) => setAgentStatus(status),
        (text) => {
          // Replace glued streaming text with the corrected final reply
          setStore((prev) => {
            if (!prev) return prev;
            const cur = getActiveConversation(prev);
            if (cur.sessionId !== sessionId) return prev;
            const msgs = cur.messages.map((m) =>
              m.id === assistantId ? { ...m, content: text } : m,
            );
            return upsertActive(prev, { messages: msgs });
          });
        },
      );
      resetNextRef.current = false;
      resetIdsRef.current.delete(sessionId);
      setEngagement(recordLearningTurn());
      const nextMem = recordLearningTurnMemory(mem, {
        userText: payload.text,
        assistantText: full,
        chatTitle: active?.title || titleFromMessages(messages),
      });
      setLearningMemory(nextMem);
      syncProfileFromSkills(profile, nextMem);
      void pushLearningMemoryToServer(nextMem);
      if (shouldSpeak) {
        speakApiRef.current?.finish(full);
      }
      // Always pin the merged final text so a streamed diagram cannot vanish
      // after done/onReplace/storage races.
      setStore((prev) => {
        if (!prev) return prev;
        const cur = getActiveConversation(prev);
        if (cur.sessionId !== sessionId) return prev;
        const msgs = cur.messages.map((m) =>
          m.id === assistantId
            ? {
                ...m,
                content: full.trim()
                  ? full
                  : m.content || "(empty reply)",
              }
            : m,
        );
        return upsertActive(prev, { messages: msgs });
      });
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Send failed";
      setError(msg);
      if (msg.includes("CURSOR_API_KEY") || msg.includes("API Key")) {
        setKeyMissing(true);
      }
      speakApiRef.current?.stop();
      setStore((prev) => {
        if (!prev) return prev;
        const cur = getActiveConversation(prev);
        if (cur.sessionId !== sessionId) return prev;
        const msgs = cur.messages.map((m) =>
          m.id === assistantId
            ? {
                ...m,
                content: m.content || `Sorry — something went wrong: ${msg}`,
              }
            : m,
        );
        return upsertActive(prev, { messages: msgs });
      });
    } finally {
      setBusy(false);
      setAgentStatus("");
      // Persist promptly when the turn ends
      window.setTimeout(() => {
        setStore((prev) => (prev ? { ...prev } : prev));
      }, 0);
    }
  };

  if (!ready || !store) {
    return (
      <div className="flex min-h-dvh items-center justify-center text-[var(--ink-muted)]">
        Loading…
      </div>
    );
  }

  if (keyMissing) {
    return (
      <div className="relative min-h-dvh">
        <div className="pointer-events-none absolute inset-0 overflow-hidden">
          <div className="atmosphere-blob atmosphere-blob-a" />
          <div className="atmosphere-blob atmosphere-blob-b" />
          <div className="atmosphere-grain" />
        </div>
        <SetupPanel onConfigured={() => setKeyMissing(false)} />
      </div>
    );
  }

  return (
    <div className="relative flex h-dvh max-h-dvh overflow-hidden">
      <div className="pointer-events-none absolute inset-0 overflow-hidden">
        <div className="atmosphere-blob atmosphere-blob-a" />
        <div className="atmosphere-blob atmosphere-blob-b" />
        <div className="atmosphere-grain" />
      </div>

      <HistorySidebar
        open={sidebarOpen}
        onClose={() => setSidebarOpen(false)}
        conversations={store.conversations}
        activeId={store.activeId}
        disabled={busy}
        onOpenConsole={handleOpenMiniConsole}
        onOpenCodeAgent={handleOpenCodeAgent}
        engagementLabel={
          engagement
            ? [
                engagementSummary(engagement),
                learningMemory
                  ? learningMemorySummary(learningMemory)
                  : null,
              ]
                .filter(Boolean)
                .join(" · ")
            : undefined
        }
        learningMemory={learningMemory}
        onNew={startNewSession}
        onSelect={selectConversation}
        onDelete={deleteConversation}
      />

      <div className="relative z-10 flex min-w-0 flex-1 flex-col overflow-hidden bg-[var(--bg0)]">
        <header className="safe-top flex w-full shrink-0 items-center justify-between gap-2 px-3 py-2 sm:px-4" style={{ minHeight: 48 }}>
          <button
            type="button"
            onClick={() => setSidebarOpen((p) => !p)}
            className="inline-flex h-10 w-10 items-center justify-center rounded-full text-[var(--ink-muted)] transition hover:bg-[var(--mist)] hover:text-[var(--ink)] focus-visible:ring-2 focus-visible:ring-[var(--teal)]"
            aria-label={sidebarOpen ? "Close menu" : "Menu"}
          >
            {sidebarOpen ? (
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
                <line x1="18" y1="6" x2="6" y2="18" />
                <line x1="6" y1="6" x2="18" y2="18" />
              </svg>
            ) : (
              <svg width="20" height="20" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round">
                <line x1="3" y1="5" x2="17" y2="5" />
                <line x1="3" y1="10" x2="17" y2="10" />
                <line x1="3" y1="15" x2="17" y2="15" />
              </svg>
            )}
          </button>
          <div className="flex min-w-0 items-center gap-1">
            <span className="font-[family-name:var(--font-display)] text-[17px] tracking-wide text-[var(--ink)] sm:text-lg">
              ✨ Spark
            </span>
            <span className="hidden text-sm text-[var(--ink-muted)] sm:inline">· Ryan</span>
          </div>
          {/* Voice toggle in header */}
          <button
            type="button"
            onClick={() => setVoiceEnabled((v) => !v)}
            className={`inline-flex h-10 w-10 items-center justify-center rounded-full transition focus-visible:ring-2 focus-visible:ring-[var(--teal)] ${
              voiceEnabled
                ? "bg-[var(--teal)]/10 text-[var(--teal)]"
                : "text-[var(--ink-muted)] hover:bg-[var(--mist)] hover:text-[var(--ink)]"
            }`}
            aria-label={voiceEnabled ? "Speak on" : "Speak off"}
            title={voiceEnabled ? "Speak on — tap to mute" : "Speak off — tap to speak"}
          >
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M12 1a3 3 0 0 0-3 3v8a3 3 0 0 0 6 0V4a3 3 0 0 0-3-3z" />
              <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
              <line x1="12" y1="19" x2="12" y2="23" />
              <line x1="8" y1="23" x2="16" y2="23" />
            </svg>
          </button>
        </header>

        <main
          ref={scrollerRef}
          className="mx-auto mt-0.5 w-full max-w-2xl min-h-0 flex-1 overflow-y-auto overscroll-contain px-1 sm:px-0"
        >
          <ChatThread messages={messages} streaming={busy} />
        </main>

        {agentStatus ? (
          <p className="mx-auto w-full max-w-3xl shrink-0 px-4 pb-1 text-xs text-[var(--teal)]">
            {agentStatus}
          </p>
        ) : null}

        {error ? (
          <div className="mx-auto mb-1 w-full max-w-2xl shrink-0 rounded-xl border border-[var(--coral)]/30 bg-[var(--coral)]/5 px-4 py-2.5">
            <p className="flex items-center gap-2 text-sm font-medium text-[var(--coral)]">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>
              {error}
            </p>
            <button
              type="button"
              onClick={() => setError("")}
              className="mt-1 text-xs text-[var(--ink-muted)] underline-offset-2 hover:underline"
            >
              Dismiss
            </button>
          </div>
        ) : null}

        <div className="shrink-0 border-t border-[var(--line)]/60 bg-[color-mix(in_srgb,var(--bg0)_82%,transparent)] backdrop-blur-md">
        <Composer
          disabled={busy}
          voiceEnabled={voiceEnabled}
          onVoiceEnabledChange={setVoiceEnabled}
          onVoiceIdChange={setVoiceId}
          onSpeakApi={setSpeakApi}
          onPrepareSpeak={async () => {
            await speakApiRef.current?.prepare();
          }}
          onSend={handleSend}
        />
        </div>
      </div>

      <MiniConsoleShell open={miniConsoleOpen} onClose={() => setMiniConsoleOpen(false)} onOpenFullConsole={handleOpenFullConsole} />
      <AgentConsolePanel open={agentPanelOpen} onClose={() => setAgentPanelOpen(false)} />
    </div>
  );
}

/** Simple dark mode toggle — reads/writes localStorage + <html> class. */
function DarkToggle() {
  const [dark, setDark] = useState(false);

  useEffect(() => {
    const stored = localStorage.getItem("spark.dark");
    const on = stored !== null ? stored === "true" : window.matchMedia("(prefers-color-scheme:dark)").matches;
    setDark(on);
  }, []);

  const toggle = () => {
    const next = !dark;
    setDark(next);
    localStorage.setItem("spark.dark", String(next));
    document.documentElement.classList.toggle("dark", next);
  };

  return (
    <button
      type="button"
      onClick={toggle}
      className="inline-flex h-10 w-10 items-center justify-center rounded-full text-[var(--ink-muted)] transition hover:bg-[var(--mist)] hover:text-[var(--ink)] focus-visible:ring-2 focus-visible:ring-[var(--teal)]"
      aria-label={dark ? "Light mode" : "Dark mode"}
      title={dark ? "Switch to light" : "Switch to dark"}
    >
      {dark ? (
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <circle cx="12" cy="12" r="4" />
          <path d="M12 2v2" /><path d="M12 20v2" /><path d="M4.93 4.93l1.41 1.41" />
          <path d="M17.66 17.66l1.41 1.41" /><path d="M2 12h2" /><path d="M20 12h2" />
          <path d="M6.34 17.66l-1.41 1.41" /><path d="M19.07 4.93l-1.41 1.41" />
        </svg>
      ) : (
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" />
        </svg>
      )}
    </button>
  );
}

