"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ChatThread } from "./ChatThread";
import { Composer, type ComposerApi } from "./Composer";
import { HistorySidebar } from "./HistorySidebar";
import { CodeAgentPanel } from "./CodeAgentPanel";
import { ThemePicker } from "./ThemePicker";
import { SetupPanel } from "./SetupPanel";
import AccountSwitcher from "./AccountSwitcher";
import { interruptHint } from "@/lib/speech-barge-in";
import {
  loadSpeakEnabled,
  loadVoiceId,
  resolveReplyLanguage,
  type TutorVoiceId,
} from "@/lib/voices";
import {
  getActiveConversation,
  loadConversations,
  MAX_MESSAGES_PER_CHAT,
  newSessionId,
  saveConversations,
  accountIdFromUrl,
  sessionIdFromUrl,
  setUrlSession,
  titleFromMessages,
} from "@/lib/storage";
import {
  deleteServerChat,
  hydrateFromServer,
  pushStoreToServer,
  repairMissingMedia,
} from "@/lib/history-sync";
import {
  engagementForPrompt,
  engagementSummary,
  loadEngagement,
  recordLearningTurn,
  type EngagementState,
} from "@/lib/engagement";
import {
  getActiveAccount,
  hydrateAccountsFromServer,
  loadAccounts,
  loadStudentProfile,
  RYAN_ACCOUNT_ID,
  switchAccount,
  syncProfileFromSkills,
  type AccountRecord,
} from "@/lib/student-profile";
import {
  hydrateLearningMemoryFromServer,
  learningMemorySummary,
  loadLearningMemory,
  pushLearningMemoryToServer,
  recordLearningTurnMemory,
  saveLearningMemory,
  serializeLearningMemoryForChat,
  autoGenerateDigest,
  appendDigestToMemory,
  type LearningMemory,
} from "@/lib/learning-memory";
import {
  deletePhotosFromVault,
  fetchMissingPhotosFromServer,
  ingestStorePhotos,
  pruneVaultToStore,
  putPhotoInVault,
  restoreStorePhotosFromVault,
  vaultIdsFromConversation,
} from "@/lib/photo-vault";
import type { ClientAttachment } from "@/lib/file-payload";
import type {
  ChatMessage,
  ConversationRecord,
  ConversationsStore,
  HistoryTurn,
} from "@/lib/types";
import type { SpeakStreamApi } from "./VoiceControls";
import { preferCompleteTutorText, hasTutorDiagram } from "@/lib/tutor-text-filter";
import {
  mergeWorksheetPlan,
  parseWorksheetPlanFence,
} from "@/lib/worksheet-planner";
import { parseScratchDiagnosisFence } from "@/lib/scratch-diagnosis";
import { parseMisconceptionFence } from "@/lib/misconceptions";
import { collapseSameDiagramImages } from "@/lib/diagram-lifecycle";
import { applyMisconceptionToMemory } from "@/lib/learning-memory";
import { inferSkillsFromText } from "@/lib/skill-catalog";
import {
  buildPracticeKickoffMessage,
  clearPracticeOffer,
  deferPracticeOffer,
  dismissPracticeOfferForToday,
  loadPracticeOffer,
  savePracticeOffer,
  type PendingPracticeOffer,
} from "@/lib/session-practice";
import {
  maybeCloseSession,
  recoverMissedSessionCloses,
  stampConversationInList,
  VISIBILITY_CLOSE_DEBOUNCE_MS,
} from "@/lib/session-close";
import {
  buildOpenerKickoffMessage,
  buildSessionOpener,
  markOpenerShown,
  type SessionOpener,
} from "@/lib/session-opener";

function messageId() {
  return `m_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

function buildHistoryPreview(messages: ChatMessage[]): HistoryTurn[] {
  return messages
    .filter((m) => m.role === "user" || m.role === "assistant")
    .filter((m) => m.content.trim())
    .slice(-8)
    .map((m) => ({
      role: m.role as "user" | "assistant",
      content: m.content.replace(/\s+/g, " ").trim().slice(0, 500),
      // Carry image data from the last 2 user turns that have photos so the model
      // can still "see" homework when the student sends text-only follow-ups.
      ...(m.role === "user" &&
      m.attachments?.some((a) => a.kind === "image" && a.dataUrl)
        ? {
            images: m.attachments
              .filter(
                (a): a is typeof a & { dataUrl: string } =>
                  a.kind === "image" && !!a.dataUrl,
              )
              .map((a) => ({
                name: a.name,
                mimeType: a.mimeType,
                data: a.dataUrl.replace(/^data:image\/\w+;base64,/, ""),
              })),
          }
        : undefined),
    }));
}

async function consumeChatStream(
  body: unknown,
  onDelta: (text: string) => void,
  onStatus?: (status: string) => void,
  onReplace?: (text: string) => void,
): Promise<string> {
  const payload = JSON.stringify(body);

  const readStream = async (res: Response): Promise<string> => {
    if (!res.body) throw new Error(`Request failed (${res.status})`);
    const reader = res.body.getReader();
    const decoder = new TextDecoder();
    let buffer = "";
    let full = "";
    let streamError = "";

    const paint = () =>
      new Promise<void>((resolve) => {
        if (typeof requestAnimationFrame === "function") {
          requestAnimationFrame(() => resolve());
        } else {
          setTimeout(resolve, 0);
        }
      });

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      const parts = buffer.split("\n\n");
      buffer = parts.pop() ?? "";

      let gotDelta = false;
      for (const part of parts) {
        const lines = part.split("\n");
        let event = "message";
        let dataLine = "";
        for (const line of lines) {
          if (line.startsWith("event:")) event = line.slice(6).trim();
          if (line.startsWith("data:")) dataLine += line.slice(5).trim();
        }
        if (!dataLine) continue;
        const data = JSON.parse(dataLine) as {
          text?: string;
          error?: string;
          status?: string;
        };
        if (event === "delta" && data.text) {
          full += data.text;
          onDelta(data.text);
          gotDelta = true;
        }
        if (event === "status" && data.status) {
          onStatus?.(data.status);
        }
        if (event === "error" && data.error) {
          streamError = data.error;
        }
        // Always prefer the server's final text — streaming deltas often glue
        // English words ("Hello" + "world" → "Helloworld" if spaces were dropped).
        // Never replace a streamed diagram with a diagram-less final.
        if (event === "done" && data.text) {
          let preferred = preferCompleteTutorText(full, data.text);
          if (hasTutorDiagram(full) && !hasTutorDiagram(preferred)) {
            preferred = full;
          }
          if (!full) {
            full = preferred;
            onDelta(preferred);
            gotDelta = true;
          } else if (preferred !== full) {
            full = preferred;
            onReplace?.(preferred);
            gotDelta = true;
          }
        }
      }
      // Let React paint between SSE chunks (critical on iPad)
      if (gotDelta) await paint();
    }

    if (streamError) throw new Error(streamError);
    return full;
  };

  for (let attempt = 0; attempt < 2; attempt += 1) {
    const res = await fetch("/api/chat", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: payload,
    });

    if (res.ok) {
      return readStream(res);
    }

    const data = (await res.json().catch(() => null)) as {
      error?: string;
    } | null;
    const msg = data?.error || `Request failed (${res.status})`;
    const retryable =
      attempt === 0 &&
      (res.status === 400 || res.status === 502 || res.status === 503) &&
      (!data?.error || /invalid json|bad request/i.test(msg));
    if (retryable) {
      await new Promise((r) => setTimeout(r, 350));
      continue;
    }
    throw new Error(msg);
  }

  throw new Error("Request failed");
}

function upsertActive(
  store: ConversationsStore,
  patch: Partial<ConversationRecord> & { messages?: ChatMessage[] },
): ConversationsStore {
  const now = Date.now();
  const idx = store.conversations.findIndex(
    (c) => c.sessionId === store.activeId,
  );
  const prev =
    idx >= 0
      ? store.conversations[idx]!
      : {
          sessionId: store.activeId,
          title: "New chat",
          messages: [],
          createdAt: now,
          updatedAt: now,
        };

  let messages = patch.messages ?? prev.messages;
  if (messages.length > MAX_MESSAGES_PER_CHAT) {
    messages = messages.slice(-MAX_MESSAGES_PER_CHAT);
  }

  const next: ConversationRecord = {
    ...prev,
    ...patch,
    messages,
    title: titleFromMessages(messages),
    updatedAt: now,
  };

  const conversations = [...store.conversations];
  if (idx >= 0) conversations[idx] = next;
  else conversations.unshift(next);

  return { ...store, conversations };
}

export function TutorShell() {
  const [ready, setReady] = useState(false);
  const [store, setStore] = useState<ConversationsStore | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [agentStatus, setAgentStatus] = useState("");
  const [keyMissing, setKeyMissing] = useState(false);
  const [voiceEnabled, setVoiceEnabled] = useState(true);
  const [voiceId, setVoiceId] = useState<TutorVoiceId>("auto");
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [agentPanelOpen, setAgentPanelOpen] = useState(false);
  const [agentPanelMinimized, setAgentPanelMinimized] = useState(false);
  const [engagement, setEngagement] = useState<EngagementState | null>(null);
  const [learningMemory, setLearningMemory] = useState<LearningMemory | null>(
    null,
  );
  const [practiceOffer, setPracticeOffer] = useState<PendingPracticeOffer | null>(
    null,
  );
  const [sessionOpener, setSessionOpener] = useState<SessionOpener | null>(null);
  const [accountName, setAccountName] = useState("");
  const [accountId, setAccountId] = useState(RYAN_ACCOUNT_ID);
  const [accounts, setAccounts] = useState<AccountRecord[]>([]);
  const [ttsSpeaking, setTtsSpeaking] = useState(false);
  const [checkMode, setCheckMode] = useState(false);
  const scrollerRef = useRef<HTMLDivElement>(null);
  const resetNextRef = useRef(false);
  /** sessionIds that need a fresh Cursor agent on next send */
  const resetIdsRef = useRef<Set<string>>(new Set());
  const speakApiRef = useRef<SpeakStreamApi | null>(null);
  const composerApiRef = useRef<ComposerApi | null>(null);
  const checkModeRef = useRef(false);
  const saveTimerRef = useRef<number | null>(null);
  const voiceEnabledRef = useRef(true);
  const voiceIdRef = useRef<TutorVoiceId>("auto");
  const accountIdRef = useRef(RYAN_ACCOUNT_ID);
  const storeRef = useRef<ConversationsStore | null>(null);
  const busyRef = useRef(false);
  const syncRunningRef = useRef(false);
  /** Gates server push until init hydration populates deletionCache (prevents
   *  tombstoned conversations from being re-uploaded on fresh page loads). */
  const hydrationDoneRef = useRef(false);
  const accountsRef = useRef<AccountRecord[]>([]);
  /** When a deep-link pinned an account, don't let roster hydrate overwrite it. */
  const deepLinkAccountRef = useRef<string | null>(null);

  useEffect(() => {
    checkModeRef.current = checkMode;
  }, [checkMode]);

  // --- Single init effect: resolve account first, then load conversations ---
  useEffect(() => {
    let cancelled = false;
    // Deferred so the synchronous init setState batch doesn't trigger
    // react-hooks/set-state-in-effect (the async work below already runs in
    // callbacks and is unaffected).
    const t = setTimeout(() => {
    try {
      // 1. Resolve account synchronously — honor ?account= deep-link first
      let accts = loadAccounts();
      const urlAccount = accountIdFromUrl();
      const urlSession = sessionIdFromUrl();
      if (
        urlAccount &&
        accts.accounts.some((a) => a.id === urlAccount) &&
        urlAccount !== accts.activeId
      ) {
        accts = switchAccount(urlAccount, accts);
        deepLinkAccountRef.current = urlAccount;
      }
      let active = getActiveAccount(accts);
      let aid = active.id;
      accountIdRef.current = aid;

      // 2. Load all per-account client data synchronously
      const enabled = loadSpeakEnabled(aid);
      const vid = loadVoiceId(aid);
      const eng = loadEngagement(aid);
      const mem = loadLearningMemory(aid);
      let conversations = loadConversations(aid);

      // Local deep-link: session already on this account
      if (urlSession && urlSession.length > 4) {
        const exists = conversations.conversations.some(
          (c) => c.sessionId === urlSession,
        );
        if (exists && conversations.activeId !== urlSession) {
          conversations = { ...conversations, activeId: urlSession };
        }
      }

      if (cancelled) return;

      // 3. Batch state updates so React renders once
      setAccountId(aid);
      setAccounts(accts.accounts);
      setAccountName(active.profile.name);
      setVoiceEnabled(enabled);
      voiceEnabledRef.current = enabled;
      setVoiceId(vid);
      voiceIdRef.current = vid;
      setEngagement(eng);
      setLearningMemory(mem);
      setStore(conversations);
      setReady(true);
      if (urlSession && urlSession.length > 4) {
        setUrlSession(urlSession, aid);
      }

      // 4. Non-blocking background work
      void hydrateLearningMemoryFromServer(aid).then((m) => {
        if (!cancelled) setLearningMemory(m);
      });

      // Hydrate accounts from server so they're shared across devices
      void hydrateAccountsFromServer().then((hydrated) => {
        if (cancelled) return;
        setAccounts(hydrated.accounts);
        // Never clobber a deep-link account with server "last active"
        if (deepLinkAccountRef.current) return;
        const fresh = getActiveAccount(hydrated);
        if (fresh.id !== accountIdRef.current) {
          setAccountId(fresh.id);
          setAccountName(fresh.profile.name);
        }
      });

      // Photo vault → server hydration; also resolve cross-account deep-links
      void (async () => {
        try {
          let workingAid = aid;
          let workingStore = conversations;

          // Session in URL but not on current account → look up owner on server
          const needLookup =
            !!urlSession &&
            urlSession.length > 4 &&
            !workingStore.conversations.some((c) => c.sessionId === urlSession);

          if (needLookup) {
            try {
              const res = await fetch(
                `/api/history?lookupSession=${encodeURIComponent(urlSession)}`,
              );
              if (res.ok) {
                const data = (await res.json()) as {
                  accountId?: string;
                  conversation?: ConversationRecord;
                };
                const ownerId = data.accountId;
                if (ownerId && ownerId !== workingAid) {
                  // Persist switch + reload that account's local store
                  const switched = switchAccount(ownerId);
                  deepLinkAccountRef.current = ownerId;
                  workingAid = ownerId;
                  accountIdRef.current = ownerId;
                  const ownerAcct = getActiveAccount(switched);
                  if (!cancelled) {
                    setAccounts(switched.accounts);
                    setAccountId(ownerId);
                    setAccountName(ownerAcct.profile.name);
                    setVoiceEnabled(loadSpeakEnabled(ownerId));
                    voiceEnabledRef.current = loadSpeakEnabled(ownerId);
                    const oVid = loadVoiceId(ownerId);
                    setVoiceId(oVid);
                    voiceIdRef.current = oVid;
                    setEngagement(loadEngagement(ownerId));
                    setLearningMemory(loadLearningMemory(ownerId));
                    void hydrateLearningMemoryFromServer(ownerId).then((m) => {
                      if (!cancelled && accountIdRef.current === ownerId) {
                        setLearningMemory(m);
                      }
                    });
                  }
                  workingStore = loadConversations(ownerId);
                }
                // Seed conversation from lookup so UI has it before full hydrate
                if (
                  data.conversation?.sessionId === urlSession &&
                  !workingStore.conversations.some(
                    (c) => c.sessionId === urlSession,
                  )
                ) {
                  workingStore = {
                    ...workingStore,
                    activeId: urlSession,
                    conversations: [
                      data.conversation,
                      ...workingStore.conversations,
                    ],
                  };
                } else if (urlSession) {
                  workingStore = { ...workingStore, activeId: urlSession };
                }
                if (!cancelled) {
                  setStore(workingStore);
                  setUrlSession(urlSession, workingAid);
                }
              }
            } catch {
              // lookup failed — continue with current account hydrate
            }
          }

          await ingestStorePhotos(workingStore);
          const merged = await hydrateFromServer(workingStore, workingAid);
          let withActive = merged;
          if (
            urlSession &&
            urlSession.length > 4 &&
            merged.conversations.some((c) => c.sessionId === urlSession) &&
            merged.activeId !== urlSession
          ) {
            withActive = { ...merged, activeId: urlSession };
          }
          const restored = await restoreStorePhotosFromVault(withActive);
          const fetched = await fetchMissingPhotosFromServer(restored);
          const { store: repaired } = await repairMissingMedia(
            fetched,
            workingAid,
          );
          const final = repaired !== fetched ? repaired : fetched;
          await ingestStorePhotos(final);
          await pruneVaultToStore(final);
          if (cancelled || accountIdRef.current !== workingAid) return;
          setStore(final);
          saveConversations(final, workingAid);
          if (urlSession && urlSession.length > 4) {
            setUrlSession(urlSession, workingAid);
          }
          const withMedia = await pushStoreToServer(final, workingAid);
          if (cancelled || accountIdRef.current !== workingAid) return;
          if (withMedia !== final) {
            setStore(withMedia);
            saveConversations(withMedia, workingAid);
          }
        } catch {
          // Background hydration failures are non-critical — the UI is already live
        } finally {
          // Allow debounce pushes now that deletionCache has been populated (or
          // the fetch definitively failed — holding the gate forever is worse).
          hydrationDoneRef.current = true;
        }
      })();

      // API key check — non-critical, defaults to server-side default key
      fetch("/api/setup")
        .then(async (r) => {
          if (cancelled) return;
          const data = (await r.json()) as { configured?: boolean };
          setKeyMissing(data.configured === false);
        })
        .catch(() => {
          if (!cancelled) setKeyMissing(false);
        });
    } catch (e) {
      // If init itself crashes, show the error instead of infinite loading
      console.error("Spark init failed", e);
      if (!cancelled) {
        setError("Something went wrong. Please refresh the page to try again.");
        setReady(true);
      }
    }
    }, 0);

    return () => {
      cancelled = true;
      clearTimeout(t);
    };
    // One-time init intentionally reads the initial accountId from the closure.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    accountIdRef.current = accountId;
  }, [accountId]);

  useEffect(() => {
    accountsRef.current = accounts;
  }, [accounts]);

  useEffect(() => {
    storeRef.current = store;
  }, [store]);

  useEffect(() => {
    busyRef.current = busy;
  }, [busy]);

  useEffect(() => {
    voiceEnabledRef.current = voiceEnabled;
  }, [voiceEnabled]);

  useEffect(() => {
    voiceIdRef.current = voiceId;
  }, [voiceId]);

  const setSpeakApi = useCallback((api: SpeakStreamApi | null) => {
    speakApiRef.current = api;
  }, []);

  // Debounce localStorage + server sync while streaming — sync writes freeze the UI on iPad
  useEffect(() => {
    if (!ready || !store) return;
    if (saveTimerRef.current) window.clearTimeout(saveTimerRef.current);
    const delay = busy ? 1500 : 280;
    saveTimerRef.current = window.setTimeout(() => {
      saveConversations(store, accountId);
      if (!busy && hydrationDoneRef.current) {
        void (async () => {
          await ingestStorePhotos(store);
          const withMedia = await pushStoreToServer(store, accountId);
          if (withMedia !== store) {
            setStore(withMedia);
          }
        })();
      }
    }, delay);
    return () => {
      if (saveTimerRef.current) window.clearTimeout(saveTimerRef.current);
    };
  }, [ready, store, busy, accountId]);

  // Periodic cross-device sync: pull deletions + new messages + account changes
  // from the server every 60s and whenever the tab becomes visible again. A
  // conversation that was deleted on another device disappears from this screen
  // without reload. New accounts created on other devices also appear.
  useEffect(() => {
    if (!ready) return;
    const sync = async () => {
      const cur = storeRef.current;
      if (!cur || busyRef.current || syncRunningRef.current) return;
      syncRunningRef.current = true;
      try {
        // 1. Sync account list (new accounts / remote deletions)
        const hydratedAccts = await hydrateAccountsFromServer();
        // Check for remote account deletions / additions
        const curAcc = accountsRef.current;
        const curIds = new Set(curAcc.map((a) => a.id));
        const acctsChanged =
          hydratedAccts.accounts.length !== curAcc.length ||
          !hydratedAccts.accounts.every((a) => curIds.has(a.id));
        // 2. Sync conversations
        const merged = await hydrateFromServer(cur, accountIdRef.current);
        const restored = await restoreStorePhotosFromVault(merged);
        const fetched = await fetchMissingPhotosFromServer(restored);
        // Upload local-only media (browser has dataUrl, server missing file)
        const { store: repaired } = await repairMissingMedia(
          fetched,
          accountIdRef.current,
        );
        const final = repaired !== fetched ? repaired : fetched;
        const convsChanged =
          final.activeId !== cur.activeId ||
          JSON.stringify(final.conversations) !==
            JSON.stringify(cur.conversations);
        if (convsChanged) {
          setStore(final);
          saveConversations(final, accountIdRef.current);
        }
        if (acctsChanged) {
          setAccounts(hydratedAccts.accounts);
          // If the active account was deleted remotely, switch to the first available
          const stillActive = hydratedAccts.accounts.some(
            (a) => a.id === accountIdRef.current,
          );
          if (!stillActive) {
            const fallback = hydratedAccts.accounts[0];
            if (fallback) {
              accountIdRef.current = fallback.id;
              setAccountId(fallback.id);
              setAccountName(fallback.profile.name);
              const nextStore = loadConversations(fallback.id);
              setStore(nextStore);
              saveConversations(nextStore, fallback.id);
            }
          }
        }
      } catch {
        // offline — next cycle retries
      } finally {
        syncRunningRef.current = false;
      }
    };
    const timer = window.setInterval(sync, 60_000);
    const onVisible = () => {
      if (document.visibilityState === "visible") void sync();
    };
    document.addEventListener("visibilitychange", onVisible);
    return () => {
      window.clearInterval(timer);
      document.removeEventListener("visibilitychange", onVisible);
    };
  }, [ready]);

  // A2.h.3 — debounced close when tab/app goes hidden (≥30s)
  useEffect(() => {
    if (!ready) return;
    let hideTimer: number | null = null;
    const onVis = () => {
      if (document.visibilityState === "hidden") {
        hideTimer = window.setTimeout(() => {
          const s = storeRef.current;
          if (!s || busyRef.current) return;
          const leaving = getActiveConversation(s);
          const mem = learningMemory || loadLearningMemory(accountIdRef.current);
          const closed = maybeCloseSession(
            leaving,
            mem,
            accountIdRef.current,
          );
          if (!closed.closed) return;
          const conversations = stampConversationInList(
            s.conversations,
            leaving.sessionId,
            closed.conversation,
          );
          const next = { ...s, conversations };
          setStore(next);
          saveConversations(next, accountIdRef.current);
          if (closed.offer) setPracticeOffer(closed.offer);
        }, VISIBILITY_CLOSE_DEBOUNCE_MS);
      } else if (hideTimer != null) {
        window.clearTimeout(hideTimer);
        hideTimer = null;
      }
    };
    document.addEventListener("visibilitychange", onVis);
    return () => {
      document.removeEventListener("visibilitychange", onVis);
      if (hideTimer != null) window.clearTimeout(hideTimer);
    };
  }, [ready, learningMemory]);

  // A2.h.4 — missed-close recovery once store is ready
  useEffect(() => {
    if (!ready || !store) return;
    const mem = learningMemory || loadLearningMemory(accountId);
    const { conversations, offer } = recoverMissedSessionCloses(
      store.conversations,
      mem,
      accountId,
    );
    const changed = conversations.some(
      (c, i) => c.practiceOfferEmittedAt !== store.conversations[i]?.practiceOfferEmittedAt,
    );
    if (!changed) return;
    const next = { ...store, conversations };
    setStore(next);
    saveConversations(next, accountId);
    if (offer && messages.length === 0) setPracticeOffer(offer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ready, accountId]);

  const active = useMemo(
    () => (store ? getActiveConversation(store) : null),
    [store],
  );
  const sessionId = active?.sessionId ?? "";
  const messages = active?.messages ?? [];

  // CA-2 / CA-3 — hydrate empty-chat offers when account or active chat changes
  useEffect(() => {
    if (!ready || !store) return;
    if (messages.length > 0) {
      setPracticeOffer(null);
      setSessionOpener(null);
      return;
    }
    const offer = loadPracticeOffer(accountId);
    setPracticeOffer(offer);
    if (!offer) {
      const mem = learningMemory || loadLearningMemory(accountId);
      setSessionOpener(buildSessionOpener(mem, accountId));
    } else {
      setSessionOpener(null);
    }
  }, [ready, store, accountId, sessionId, messages.length, learningMemory]);

  // Esc closes sidebar
  useEffect(() => {
    if (!sidebarOpen) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setSidebarOpen(false);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [sidebarOpen]);

  const handleOpenCodeAgent = useCallback(() => { setAgentPanelOpen(true); setAgentPanelMinimized(false); }, []);

  const handleSwitchAccount = (id: string) => {
    if (id === accountId || busy) return;
    // Prevent in-flight init photo vault from overwriting the new account's store
    accountIdRef.current = id;
    // Save current state
    if (store) saveConversations(store, accountId);
    if (learningMemory) {
      saveLearningMemory(learningMemory, accountId);
      void pushLearningMemoryToServer(learningMemory, accountId);
    }
    // Switch
    const updatedStore = switchAccount(id);
    const switchedAcct = getActiveAccount(updatedStore);
    setAccounts(updatedStore.accounts);
    setAccountId(id);
    setAccountName(switchedAcct.profile.name);
    // Reload all per-account data
    setVoiceEnabled(loadSpeakEnabled(id));
    voiceEnabledRef.current = loadSpeakEnabled(id);
    const vid = loadVoiceId(id);
    setVoiceId(vid);
    voiceIdRef.current = vid;
    setEngagement(loadEngagement(id));
    const mem = loadLearningMemory(id);
    setLearningMemory(mem);
    void hydrateLearningMemoryFromServer(id).then(setLearningMemory);
    // Reset chat to new account's conversations
    const nextStore = loadConversations(id);
    setStore(nextStore);
    setError("");
    speakApiRef.current?.stop();
    if (nextStore.conversations.length > 0) {
      setUrlSession(nextStore.activeId, id);
    }
    // Background: hydrate new account's conversations from server, restore
    // photos from vault, and fetch any still-missing photos from server media.
    void (async () => {
      const merged = await hydrateFromServer(nextStore, id);
      const restored = await restoreStorePhotosFromVault(merged);
      const fetched = await fetchMissingPhotosFromServer(restored);
      // Upload local-only media that the server no longer has
      const { store: repaired } = await repairMissingMedia(fetched, id);
      const final = repaired !== fetched ? repaired : fetched;
      if (accountIdRef.current !== id) return;
      setStore(final);
      saveConversations(final, id);
      await ingestStorePhotos(final);
      void pushStoreToServer(final, id);
    })();
  };

  const startNewSession = () => {
    if (!store || busy) return;

    // Generate a digest for the session we're leaving (if it has meaningful messages)
    const prevActive = getActiveConversation(store);
    const mem = learningMemory || loadLearningMemory(accountId);
    if (prevActive && prevActive.messages.length >= 2) {
      const digest = autoGenerateDigest(
        prevActive.messages.map((m) => ({
          role: m.role === "assistant" ? "assistant" : "user",
          content: m.content,
        })),
        prevActive.title,
      );
      if (digest) {
        const nextMem = appendDigestToMemory(mem, digest);
        setLearningMemory(nextMem);
        saveLearningMemory(nextMem, accountId);
        void pushLearningMemoryToServer(nextMem, accountId);
      }
    }

    // A2.h — shared session-close (practice offer, idempotent)
    let conversations = store.conversations;
    if (prevActive) {
      const closed = maybeCloseSession(prevActive, mem, accountId);
      if (closed.closed) {
        conversations = stampConversationInList(
          conversations,
          prevActive.sessionId,
          closed.conversation,
        );
      }
      if (closed.offer) {
        setPracticeOffer(closed.offer);
      }
    }

    const id = newSessionId();
    resetIdsRef.current.add(id);
    resetNextRef.current = true;
    const now = Date.now();
    // Drop other empty chats so the list stays tidy
    const kept = conversations.filter((c) => c.messages.length > 0);
    setStore({
      version: 3,
      activeId: id,
      conversations: [
        {
          sessionId: id,
          title: "New chat",
          messages: [],
          createdAt: now,
          updatedAt: now,
        },
        ...kept,
      ],
    });
    setError("");
    speakApiRef.current?.stop();
    setUrlSession(id, accountId);

    // CA-3 — once/day opener on empty new chat (practice offer takes precedence in UI)
    const opener = buildSessionOpener(mem, accountId);
    setSessionOpener(opener);
  };

  const selectConversation = (id: string) => {
    if (!store || busy || id === store.activeId) return;
    speakApiRef.current?.stop();
    const mem = learningMemory || loadLearningMemory(accountId);
    const leaving = getActiveConversation(store);
    let conversations = store.conversations;
    if (leaving && leaving.sessionId !== id) {
      const closed = maybeCloseSession(leaving, mem, accountId);
      if (closed.closed) {
        conversations = stampConversationInList(
          conversations,
          leaving.sessionId,
          closed.conversation,
        );
      }
      if (closed.offer) setPracticeOffer(closed.offer);
    }
    setStore({ ...store, activeId: id, conversations });
    setUrlSession(id, accountId);
    setError("");
    resetNextRef.current = resetIdsRef.current.has(id);
  };

  const deleteConversation = (id: string) => {
    if (!store || busy) return;
    const doomed = store.conversations.find((c) => c.sessionId === id);
    let conversations = store.conversations.filter((c) => c.sessionId !== id);
    let activeId = store.activeId;
    if (activeId === id) {
      if (conversations.length === 0) {
        const nid = newSessionId();
        resetIdsRef.current.add(nid);
        resetNextRef.current = true;
        const now = Date.now();
        conversations = [
          {
            sessionId: nid,
            title: "New chat",
            messages: [],
            createdAt: now,
            updatedAt: now,
          },
        ];
        activeId = nid;
      } else {
        activeId = [...conversations].sort(
          (a, b) => b.updatedAt - a.updatedAt,
        )[0]!.sessionId;
        resetNextRef.current = resetIdsRef.current.has(activeId);
      }
    }
    resetIdsRef.current.delete(id);
    speakApiRef.current?.stop();
    const nextStore = { version: 3 as const, activeId, conversations };
    setStore(nextStore);
    setUrlSession(activeId, accountId);
    setError("");
    // Drop server JSON + data/media, and local IndexedDB photos for this chat
    void deleteServerChat(id, accountId);
    if (doomed) {
      void deletePhotosFromVault(vaultIdsFromConversation(doomed));
    }
    void pruneVaultToStore(nextStore);
  };

  const handleSend = async (payload: {
    text: string;
    attachments: ClientAttachment[];
  }) => {
    if (busy || !store || !sessionId) return;
    setBusy(true);
    setError("");
    setAgentStatus("Thinking…");

    // B1.h — any student turn (homework photo/text) yields the ZPD opener for the day
    if (sessionOpener) {
      markOpenerShown(accountId);
      setSessionOpener(null);
    }

    const needReset =
      resetNextRef.current || resetIdsRef.current.has(sessionId);
    const history = buildHistoryPreview(messages);
    const shouldSpeak = voiceEnabledRef.current;

    // Vault attachments immediately so history stays viewable / downloadable
    for (const a of payload.attachments) {
      if (a.dataUrl) {
        void putPhotoInVault({
          id: a.id,
          dataUrl: a.dataUrl,
          mimeType: a.mimeType,
          name: a.name,
        });
      }
    }
    const userMsg: ChatMessage = {
      id: messageId(),
      role: "user",
      content: payload.text,
      attachments: payload.attachments.map((a) => ({
        id: a.id,
        name: a.name,
        mimeType: a.mimeType,
        kind: a.kind,
        dataUrl: a.dataUrl,
      })),
      createdAt: Date.now(),
    };
    const assistantId = messageId();
    const nextMessages: ChatMessage[] = [
      ...messages,
      userMsg,
      { id: assistantId, role: "assistant", content: "", createdAt: Date.now() },
    ];

    setStore((prev) =>
      prev
        ? upsertActive(
            { ...prev, activeId: sessionId },
            { messages: nextMessages },
          )
        : prev,
    );

    if (shouldSpeak) {
      speakApiRef.current?.begin();
    }

    try {
      const profile = loadStudentProfile();
      const mem = learningMemory || loadLearningMemory(accountId);
      const eng = engagement || loadEngagement(accountId);
      const recentTitles = store.conversations
        .filter((c) => c.sessionId !== sessionId && c.messages.length > 0)
        .sort((a, b) => b.updatedAt - a.updatedAt)
        .slice(0, 5)
        .map((c) => c.title)
        .filter((t) => t && t !== "New chat");

      const full = await consumeChatStream(
        {
          sessionId,
          message: payload.text,
          reset: needReset,
          history: needReset ? undefined : history,
          recentTitles,
          studentProfile: profile,
          learningMemory: serializeLearningMemoryForChat(mem),
          engagement: engagementForPrompt(eng),
          voiceId: voiceIdRef.current,
          replyLanguage: resolveReplyLanguage(
            voiceIdRef.current,
            payload.text,
            profile.preferredChinese,
          ),
          checkMode: checkModeRef.current === true,
          attachments: payload.attachments.map((a) => ({
            name: a.name,
            mimeType: a.mimeType,
            kind: a.kind,
            data: a.data,
            textContent: a.textContent,
          })),
        },
        // rAF-batched onDelta: group SSE deltas into one React state update
        // per animation frame to cut re-renders from 100+/sec to 60/sec
        // and eliminate screen flicker during streaming.
        (() => {
          let pendingDelta = "";
          let pendingRafId: number | undefined;
          return (delta: string) => {
            setAgentStatus("");
            // Feed every raw delta to TTS immediately for fluid speech
            if (shouldSpeak) {
              speakApiRef.current?.push(delta);
            }
            pendingDelta += delta;
            if (pendingRafId !== undefined) return; // already scheduled
            pendingRafId = requestAnimationFrame(() => {
              pendingRafId = undefined;
              const batch = pendingDelta;
              pendingDelta = "";
              if (!batch) return;
              setStore((prev) => {
                if (!prev) return prev;
                const cur = getActiveConversation(prev);
                if (cur.sessionId !== sessionId) return prev;
                const msgs = cur.messages.map((m) =>
                  m.id === assistantId
                    ? { ...m, content: m.content + batch }
                    : m,
                );
                return upsertActive(prev, { messages: msgs });
              });
            });
          };
        })(),
        (status) => setAgentStatus(status),
        (text) => {
          // Replace glued streaming text with the corrected final reply
          setStore((prev) => {
            if (!prev) return prev;
            const cur = getActiveConversation(prev);
            if (cur.sessionId !== sessionId) return prev;
            const msgs = cur.messages.map((m) =>
              m.id === assistantId ? { ...m, content: text } : m,
            );
            return upsertActive(prev, { messages: msgs });
          });
        },
      );
      resetNextRef.current = false;
      resetIdsRef.current.delete(sessionId);
      setEngagement(recordLearningTurn(undefined, accountId));
      let nextMem = recordLearningTurnMemory(mem, {
        userText: payload.text,
        assistantText: full,
        chatTitle: active?.title || titleFromMessages(messages),
      });
      // CA-6 — merge misconception fence into skill hits
      const mcHit = parseMisconceptionFence(full);
      if (mcHit) {
        const skillGuess =
          inferSkillsFromText([payload.text, full].join("\n"))[0]?.id;
        nextMem = applyMisconceptionToMemory(nextMem, skillGuess, mcHit);
        saveLearningMemory(nextMem, accountId);
      }
      // CA-5 — parse scratch diagnosis (drives prompt via next turns; strip in UI)
      parseScratchDiagnosisFence(full);
      setLearningMemory(nextMem);
      syncProfileFromSkills(profile, nextMem);
      void pushLearningMemoryToServer(nextMem, accountId);

      if (shouldSpeak) {
        speakApiRef.current?.finish(full);
      }
      // Always pin the merged final text so a streamed diagram cannot vanish
      // after done/onReplace/storage races. CA-1: also merge worksheet plan.
      // CA-8: collapse same-diagramId revisions inside the assistant message.
      const plan = parseWorksheetPlanFence(full);
      const pinned = full.trim()
        ? collapseSameDiagramImages(full)
        : "";
      setStore((prev) => {
        if (!prev) return prev;
        const cur = getActiveConversation(prev);
        if (cur.sessionId !== sessionId) return prev;
        const msgs = cur.messages.map((m) =>
          m.id === assistantId
            ? {
                ...m,
                content: pinned || m.content || "(empty reply)",
              }
            : m,
        );
        const merged = plan
          ? mergeWorksheetPlan(cur.worksheetPlan, plan)
          : cur.worksheetPlan;
        return upsertActive(prev, {
          messages: msgs,
          worksheetPlan: merged ?? undefined,
        });
      });
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Send failed";
      setError(msg);
      if (msg.includes("CURSOR_API_KEY") || msg.includes("API Key")) {
        setKeyMissing(true);
      }
      speakApiRef.current?.stop();
      setStore((prev) => {
        if (!prev) return prev;
        const cur = getActiveConversation(prev);
        if (cur.sessionId !== sessionId) return prev;
        const msgs = cur.messages.map((m) =>
          m.id === assistantId
            ? {
                ...m,
                content: m.content || `Sorry — something went wrong: ${msg}`,
              }
            : m,
        );
        return upsertActive(prev, { messages: msgs });
      });
    } finally {
      setBusy(false);
      setAgentStatus("");
      // Persist promptly when the turn ends
      window.setTimeout(() => {
        setStore((prev) => (prev ? { ...prev } : prev));
      }, 0);
    }
  };

  if (!ready || !store) {
    return (
      <div className="flex min-h-dvh items-center justify-center text-[var(--ink-muted)]">
        {error ? (
          <div className="flex flex-col items-center gap-3 px-4 text-center">
            <div className="text-4xl">&#x26A0;</div>
            <p className="text-sm max-w-xs">{error}</p>
            <button
              type="button"
              onClick={() => window.location.reload()}
              className="rounded-full bg-[var(--teal)] px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-[var(--teal)]/90 active:scale-95"
            >
              Refresh Page
            </button>
          </div>
        ) : (
          <>Loading…</>
        )}
      </div>
    );
  }

  if (keyMissing) {
    return (
      <div className="relative min-h-dvh">
        <div className="pointer-events-none absolute inset-0 overflow-hidden">
          <div className="atmosphere-blob atmosphere-blob-a" />
          <div className="atmosphere-blob atmosphere-blob-b" />
          <div className="atmosphere-grain" />
        </div>
        <SetupPanel onConfigured={() => setKeyMissing(false)} />
      </div>
    );
  }

  return (
    <div className="relative flex h-dvh max-h-dvh overflow-hidden">
      <div className="pointer-events-none absolute inset-0 overflow-hidden">
        <div className="atmosphere-blob atmosphere-blob-a" />
        <div className="atmosphere-blob atmosphere-blob-b" />
        <div className="atmosphere-grain" />
      </div>

      <HistorySidebar
        open={sidebarOpen}
        onClose={() => setSidebarOpen(false)}
        conversations={store.conversations}
        activeId={store.activeId}
        disabled={busy}
        onOpenCodeAgent={handleOpenCodeAgent}
        engagementLabel={
          engagement
            ? [
                engagementSummary(engagement),
                learningMemory
                  ? learningMemorySummary(learningMemory)
                  : null,
              ]
                .filter(Boolean)
                .join(" · ")
            : undefined
        }
        learningMemory={learningMemory}
        checkMode={checkMode}
        onCheckModeChange={setCheckMode}
        onNew={startNewSession}
        onSelect={selectConversation}
        onDelete={deleteConversation}
      />

      <div className="relative z-10 flex min-w-0 flex-1 flex-col overflow-hidden bg-[var(--bg0)]">
        {checkMode ? (
          <div className="flex shrink-0 items-center justify-between gap-2 border-b border-[var(--coral)]/30 bg-[var(--coral)]/10 px-3 py-2 sm:px-4">
            <p className="text-sm font-medium text-[var(--coral)]">
              Check mode — answers shown
            </p>
            <button
              type="button"
              onClick={() => setCheckMode(false)}
              className="min-h-11 shrink-0 rounded-lg border border-[var(--coral)]/40 px-3 text-sm font-medium text-[var(--coral)] focus-visible:ring-2 focus-visible:ring-[var(--teal)]"
            >
              Exit
            </button>
          </div>
        ) : null}
        <header className="safe-top flex w-full shrink-0 items-center gap-2 px-3 py-2 sm:px-4" style={{ minHeight: 48 }}>
          <button
            type="button"
            onClick={() => setSidebarOpen((p) => !p)}
            className="inline-flex h-10 w-10 items-center justify-center rounded-full text-[var(--ink-muted)] transition hover:bg-[var(--mist)] hover:text-[var(--ink)] focus-visible:ring-2 focus-visible:ring-[var(--teal)]"
            aria-label={sidebarOpen ? "Close menu" : "Menu"}
          >
            {sidebarOpen ? (
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
                <line x1="18" y1="6" x2="6" y2="18" />
                <line x1="6" y1="6" x2="18" y2="18" />
              </svg>
            ) : (
              <svg width="20" height="20" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round">
                <line x1="3" y1="5" x2="17" y2="5" />
                <line x1="3" y1="10" x2="17" y2="10" />
                <line x1="3" y1="15" x2="17" y2="15" />
              </svg>
            )}
          </button>
          <span className="flex-1 truncate text-center font-[family-name:var(--font-display)] text-[17px] tracking-wide text-[var(--ink)] sm:text-lg">
            ✨ The Answer Book
          </span>
          <div className="flex items-center gap-1.5">
            <button
              type="button"
              onClick={() => setVoiceEnabled((v) => !v)}
              className={`inline-flex h-10 w-10 items-center justify-center rounded-full transition focus-visible:ring-2 focus-visible:ring-[var(--teal)] ${
                voiceEnabled
                  ? "bg-[var(--teal)]/10 text-[var(--teal)]"
                  : "text-[var(--ink-muted)] hover:bg-[var(--mist)] hover:text-[var(--ink)]"
              }`}
              aria-label={voiceEnabled ? "Speak on" : "Speak off"}
              title={voiceEnabled ? "Speak on — tap to mute" : "Speak off — tap to speak"}
            >
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M12 1a3 3 0 0 0-3 3v8a3 3 0 0 0 6 0V4a3 3 0 0 0-3-3z" />
                <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
                <line x1="12" y1="19" x2="12" y2="23" />
                <line x1="8" y1="23" x2="16" y2="23" />
              </svg>
            </button>
            <ThemePicker />
            <AccountSwitcher
              accounts={accounts}
              activeId={accountId}
              accountName={accountName}
              onSwitch={handleSwitchAccount}
              onManage={() => { window.location.href = "/account"; }}
            />
          </div>
        </header>

        <main
          ref={scrollerRef}
          className="mx-auto mt-0.5 w-full max-w-2xl min-h-0 flex-1 overflow-y-auto overscroll-contain px-1 sm:px-0"
        >
          <ChatThread
            messages={messages}
            streaming={busy}
            worksheetPlan={active?.worksheetPlan ?? null}
            practiceOffer={
              messages.length === 0 ? practiceOffer : null
            }
            sessionOpener={
              messages.length === 0 && !practiceOffer ? sessionOpener : null
            }
            onPractice={() => {
              if (!practiceOffer) return;
              const text = buildPracticeKickoffMessage(practiceOffer.targets);
              clearPracticeOffer(accountId);
              setPracticeOffer(null);
              markOpenerShown(accountId);
              setSessionOpener(null);
              void handleSend({ text, attachments: [] });
            }}
            onPracticeTomorrow={() => {
              if (!practiceOffer) return;
              const deferred = deferPracticeOffer(practiceOffer);
              savePracticeOffer(deferred);
              setPracticeOffer(null);
            }}
            onPracticeDismiss={() => {
              dismissPracticeOfferForToday(accountId);
              setPracticeOffer(null);
            }}
            onOpenerTry={() => {
              if (!sessionOpener) return;
              const text = buildOpenerKickoffMessage(sessionOpener);
              markOpenerShown(accountId);
              setSessionOpener(null);
              void handleSend({ text, attachments: [] });
            }}
            onSnapHomework={() => {
              if (sessionOpener) {
                markOpenerShown(accountId);
                setSessionOpener(null);
              }
              composerApiRef.current?.openCamera();
            }}
          />
        </main>

        {agentStatus ? (
          <p className="mx-auto w-full max-w-3xl shrink-0 px-4 pb-1 text-xs text-[var(--teal)]">
            {agentStatus}
          </p>
        ) : null}

        {error ? (
          <div className="mx-auto mb-1 w-full max-w-2xl shrink-0 rounded-xl border border-[var(--coral)]/30 bg-[var(--coral)]/5 px-4 py-2.5">
            <p className="flex items-center gap-2 text-sm font-medium text-[var(--coral)]">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>
              {error}
            </p>
            <button
              type="button"
              onClick={() => setError("")}
              className="mt-1 text-xs text-[var(--ink-muted)] underline-offset-2 hover:underline"
            >
              Dismiss
            </button>
          </div>
        ) : null}

        <div className="shrink-0 border-t border-[var(--line)]/60 bg-[color-mix(in_srgb,var(--bg0)_82%,transparent)] backdrop-blur-md">
        <Composer
          disabled={busy}
          voiceEnabled={voiceEnabled}
          onVoiceEnabledChange={setVoiceEnabled}
          onVoiceIdChange={setVoiceId}
          onSpeakApi={setSpeakApi}
          onComposerApi={(api) => {
            composerApiRef.current = api;
          }}
          speakStatus={ttsSpeaking ? interruptHint(true) : undefined}
          onSpeakingChange={setTtsSpeaking}
          recentSkillIds={
            learningMemory
              ? [...learningMemory.skills]
                  .sort((a, b) => b.lastSeen - a.lastSeen)
                  .slice(0, 6)
                  .map((s) => s.id)
              : []
          }
          onPrepareSpeak={async () => {
            await speakApiRef.current?.prepare();
          }}
          onSend={handleSend}
        />
        </div>
      </div>

      <CodeAgentPanel
        open={agentPanelOpen && !agentPanelMinimized}
        onClose={() => { setAgentPanelOpen(false); setAgentPanelMinimized(false); }}
        onMinimize={() => setAgentPanelMinimized(true)}
      />

      {/* Floating bubble when minimized — click to restore */}
      {agentPanelOpen && agentPanelMinimized && (
        <button
          type="button"
          onClick={() => setAgentPanelMinimized(false)}
          className="fixed bottom-5 right-5 z-40 flex h-12 w-12 items-center justify-center rounded-full bg-[var(--teal)] text-white shadow-lg hover:brightness-110 transition-all animate-fade-up"
          aria-label="Restore code agent"
          title="Code Agent"
        >
          <span className="text-lg">🤖</span>
        </button>
      )}
    </div>
  );
}

